project:
  type: website
  output-dir: docs

website:
  title: "randridge.github.io"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      # - text: About
      #   href: about.qmd
      - text: "PUBHBIO 7225"
        href: PUBHBIO7225.qmd
      - text: "CV"
        href: RebeccaAndridge_CV.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

