---
title: "Rebecca R. Andridge"
format:
  html:
    toc: true
  pdf:
    author: Rebecca R. Andridge
    pdf-engine: weasyprint
css: custom_cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
## CONTACT INFORMATION

[College of Public Health, Division of Biostatistics](https://cph.osu.edu/biostatistics)<br> [The Ohio State University](http://www.osu.edu/)<br> *Phone:* (614) 247-7912<br> *E-mail:* [andridge.1\@osu.edu](mailto:andridge.1@osu.edu)<br> 242 Cunz Hall, 1841 Neil Avenue<br> Columbus, OH 43210 USA
:::

## RESEARCH INTERESTS

Missing data: multiple imputation, nonignorable nonresponse, hot deck imputation; Survey sampling; Nonprobability sampling; Statistical issues surrounding group randomized trials; Collaborative research in behavioral medicine, psychology, and cancer

## EDUCATION

**University of Michigan**<br>

-   Ph.D., Biostatistics, August 2009<br>
    -   Dissertation: *Statistical Methods for Missing Data in Complex Sample Surveys*<br>
    -   Advisor: Dr. Roderick J. A. Little<br>
-   M.S., Biostatistics, April 2005

**Stanford University**<br>

-   B.A., Economics (Minor: Psychology), April 1999

## POSITIONS

**Associate Dean for Undergraduate Studies** [8/2024 -- present]{.cvdate}<br> College of Public Health<br> The Ohio State University

**Professor** [5/2024 -- present]{.cvdate}<br> **Associate Professor** [6/2016 -- 5/2024]{.cvdate}<br> **Assistant Professor** [9/2009 -- 6/2016]{.cvdate}<br> Division of Biostatistics, College of Public Health<br> The Ohio State University

**Faculty Fellow for External Engagement (0.2 FTE)** [8/2023 -- 5/2024]{.cvdate}<br> Office of Academic Affairs<br> The Ohio State University<br> *Key activities: Assist OAA External Engagement with reviewing current regional campus policies and recommending and/or developing standardized faculty policies, procedures, and expectations.*

**Faculty Fellow for Distance Education (0.25 FTE)** [8/2019 -- 8/2021]{.cvdate}<br> Office of Academic Affairs<br> The Ohio State University<br> *Key activities: Led University-wide central review of courses seeking "emergency" approval for online delivery in Summer 2020 (COVID); Developed rubric for peer evaluation of online teaching; Assisted with development of data dashboards for University-wide data on course delivery mode; Provided faculty input for various initiatives in the Office for Distance Education and E-Learning.*

**Instructor** [9/2007 -- 8/2008]{.cvdate}<br> Biostatistics Department<br> University of Michigan\>

**Graduate Student Research Assistant** [9/2005 -- 8/2008]{.cvdate}<br> Biostatistics Department<br> University of Michigan

**Graduate Student Research Assistant** [9/2003 -- 8/2008]{.cvdate}<br> Health Behavior and Health Education Department<br> University of Michigan

::: print-only
## AFFILIATIONS

The Ohio State University Decision Sciences Collaborative [2015 -- present]{.cvdate}<br> The Ohio State University Food Innovation Center [2013 -- present]{.cvdate}<br> The Ohio State University Institute for Population Research [2012 -- present]{.cvdate}
:::

## HONORS AND AWARDS

-   Elected Fellow, American Statistical Association, 2020<br> *For influential research on missing data, outstanding collaborative research, superb and innovative classroom and distance teaching of statistics, and editorial service to the profession.*
-   Ohio State University Institute for Teaching and Learning Endorsement: Mentoring Faculty, 2018.
-   Poster Award winner, American Statistical Association Survey Research Methods Section, Joint Statistical Meetings, 2011.
-   Ohio State University College of Public Health Excellence in Teaching Award, 2011
-   University of Michigan Rackham Predoctoral Fellowship, 2008 -- 2009.
-   University of Michigan Graduate School Travel Grant, 2008.
-   Travel Award, American Statistical Association Survey Research Methods Section, 2008.
-   NIH Predoctoral Cancer Research Training Grant, 2005 -- 2008

## COURSES TAUGHT

**The Ohio State University**

*Undergraduate*

-   Biostatistics for Public Health Research (PUBHBIO 2210)
    -   Spring 2013, Autumn 2013, Spring 2015
    -   Student Evaluation of Instruction (SEI) overall scores (out of 5): 5, 4.9, 5
-   Public Health Capstone (Internship/Research) (PUBHLTH 3191/3999)
    -   Autumn 2024
    -   SEI overall scores (out of 5): 4.7

*Graduate*

-   Design and Analysis of Studies in the Health Sciences I (PUBHBIO 701/6210)
    -   Autumn 2010, Autumn 2011, Autumn 2012, Autumn 2014, Spring 2015, Autumn 2015, Spring 2016, Spring 2021
    -   SEI overall scores (out of 5): 4.9, 5.0, 4.9, 4.8, 4.9, 5.0, 5.0, 4.9
-   Design and Analysis of Studies in the Health Sciences II (PUBHBIO 702/6211)
    -   Winter 2010, Spring 2010, Winter 2011, Winter 2012, Spring 2017, Spring 2018
    -   SEI overall scores (out of 5): 4.9, 5.0, 4.9, 5.0, 4.9, 4.9
-   Regression Methods for the Health Sciences (PUBHBIO 6250)
    -   Autumn 2024
    -   SEI overall score (out of 5): 4.8
-   Methods in Quantitative Data Analysis (PUBHLTH 6001)
    -   Autumn 2021, Autumn 2022
    -   SEI overall score (out of 5): 4.9, 4.8
-   Ethics in Biostatistics (PUBHBIO 6260)
    -   Autumn 2021, Autumn 2022
    -   SEI overall scores (out of 5): N/A (below response count threshold), 5.0
-   Survey Sampling Methods (PUBHBIO 7225)
    -   Autumn 2019, Autumn 2023, Autumn 2025
    -   SEI overall score (out of 5): 5.0, 5.0
    -   Survey of the Student Learning Experience (SSLE) mean score range (out of 5): 4.9-4.9 (AU25)
-   Doctoral Seminar (PUBHBIO 8899)
    -   Autumn 2013
    -   SEI overall score (out of 5): N/A (below response count threshold)
-   Basic Biostatistics (PUBHLTH 670.03/7350.03) (CPH Summer Program, 1 week)
    -   Summer 2011, Summer 2013

**University of Michigan**

*Graduate*

-   Computer Packages (BIOSTAT 511)
    -   Fall 2007--Summer 2008
