<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <title>randridge.github.io – Domain Estimation</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-37dd58ee8260662a2db356013c91c3b1.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Domain Estimation</h1>
  <p class="subtitle">PUBHBIO 7225 Lecture 16</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="outline" class="slide level2">
<h2>Outline</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Topics</strong></p>
<ul>
<li><p>Domain Estimation</p></li>
<li><p>Chi-Square Tests</p></li>
<li><p>Discussion of Individual Project (time-permitting)</p></li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>Activities</strong></p>
<ul>
<li>16.1 Domain Estimation/Comparison</li>
</ul>
</div></div>
<p><strong>Readings</strong></p>
<ul>
<li>West BT, Berglund P, Heeringa SG (2008). A closer examination of subpopulation analysis of complex-sample survey data. <em>The Stata Journal</em>, 8(4); 520-531. (PDF on Carmen)</li>
</ul>
<p><strong>Assignments</strong></p>
<ul>
<li>Problem Set 4 due Thursday 10/23/2025 11:59pm via Carmen</li>
</ul>
</section>
<section id="estimation-in-domains" class="slide level2 pause">
<h2>Estimation in Domains</h2>
<blockquote>
<p><span class="alert3"><strong>Domain</strong></span> = a subgroup in the population that is not part of the sampling design.<br>
Also called <span class="alert3">subpopulations</span> or <span class="alert3">subgroups</span> or <span class="alert3">subclasses</span>.</p>
</blockquote>
<ul>
<li><p>Not a stratum, not a cluster/group of clusters</p>
<ul>
<li><p>Domains can cross strata (and often/usually do)</p></li>
<li><p>Domains can include units from many clusters (but maybe not all clusters)</p></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p><em>Like</em> strata and clusters, each unit <span class="math inline">\(i\)</span> either belongs to a certain domain or does not belong to the domain</p></li>
<li><p><em>Unlike</em> strata and clusters, we don’t know what domain unit <span class="math inline">\(i\)</span> belongs to until it is sampled (i.e., record domain membership on the survey)</p></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>Examples:</p>
<ul>
<li><p>SRS of OSU students on Columbus campus, domain = students who live off-campus</p></li>
<li><p>Stratified (by county) random sample of women who recently gave birth in Ohio, domain = women who did not have a prenatal visit</p></li>
<li><p>Two-stage cluster sample of students within schools, domain = students with a disclosed disability</p></li>
</ul></li>
</ul>
</div>
</section>
<section id="domain-sample-sizes-are-random-variables" class="slide level2 pause">
<h2>Domain Sample Sizes are Random Variables</h2>
<ul>
<li><p><strong>Key Point:</strong> The number of units in the domain in a sample is a <span class="alert2"><strong>random variable</strong></span></p>
<ul>
<li><p>Take another sample, get a different number of units in the domain</p>
<ul>
<li>Contrast with a stratum – take another sample, get the same number of units in the stratum!</li>
</ul></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p>Formula for the variance of a domain total incorporates this sample-to-sample variability</p>
<ul>
<li><p>Statistical software must recognize (be told about / have info about) all the original design strata and PSUs – even if some don’t include any domain members</p></li>
<li><p>Thus, you must <strong>never subset your data for analysis</strong></p></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>Subsetting will definitely cause problems when:</p>
<ul>
<li><p>A stratum does not contain any members of the domain</p>
<ul>
<li>Usually unlikely to occur – but possible in highly stratified designs</li>
</ul></li>
<li><p>A PSU does not contain any members of a domain</p>
<ul>
<li>Quite possible – imagine sampling households, and the domain is males aged 50+</li>
</ul></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><strong>One exception:</strong> It’s okay to subset an SRS – an SRS of a population contains SRS of a subpopulation</li>
</ul>
</div>
</section>
<section id="domain-indicators" class="slide level2">
<h2>Domain Indicators</h2>
<ul>
<li><p>Indicator variable, <span class="math inline">\(x_i\)</span>, for domain membership: <span class="math display">\[x_i = \begin{cases} 1 &amp; \text{unit $i$ is in domain $d$}\\
0 &amp; \text{unit $i$ not in domain $d$}
\end{cases}\]</span></p></li>
<li><p>Estimates:</p>
<ul>
<li><p>Domain total: &nbsp; <span class="math inline">\(\displaystyle \hat{t}^{(d)} = \sum_{i \in \mathcal{S}} w_i x_i y_i\)</span></p></li>
<li><p>Domain mean: &nbsp; <span class="math inline">\(\displaystyle \bar{y}^{(d)} = \frac{\sum_{i \in \mathcal{S}} w_i x_i y_i}{\sum_{i \in \mathcal{S}} w_i x_i}\)</span></p></li>
</ul></li>
</ul>
<p>
</p><ul>
<li><p><strong>Same point estimate</strong> as if you dropped the non-domain units (<span class="math inline">\(x_i=0\)</span> for units not in the domain)</p></li>
<li><p>But variance estimation would be <strong>incorrect</strong></p></li>
<li><p><strong>You must use the whole sample for estimation</strong></p></li>
</ul>
</section>
<section id="example-domain-estimation-in-nhamcs" class="slide level2 pause">
<h2>Example: Domain Estimation in NHAMCS</h2>
<ul>
<li><p>Analysis of data from the 2004 National Hospital Ambulatory Medical Care Survey (paper on Carmen)</p></li>
<li><p>NHAMCS collects data on the use and provision of ambulatory care services in hospital emergency departments (ED) and outpatient departments and ambulatory surgery locations</p></li>
<li><p>4-stage design with stratification:</p>
<ol type="1">
<li><p>PSUs = geographic areas (selection via PPS) (stratified by SES variables)</p></li>
<li><p>hospitals within PSUs (selection via PPS)</p></li>
<li><p>clinics within hospitals (complex selection procedure involving PPS)</p></li>
<li><p>patient visits within clinics (systematic sampling)</p></li>
</ol></li>
<li><p>2004 sample had <span class="alert">8 strata</span> and <span class="alert">294 PSUs</span> (between 6 and 86 PSUs per stratum)</p></li>
</ul>
<div class="fragment">
<ul>
<li><p><strong>Domain of interest:</strong> visits to EDs by elderly (age <span class="math inline">\(\geq\)</span> 60) African-American males</p>
<ul>
<li>Domain members could theoretically appear across the strata and PSUs – but there are likely PSUs with no domain members</li>
</ul></li>
<li><p><strong>Goal:</strong> estimate the percentage of visits in this domain with dizziness or vertigo as a reason for the visit</p></li>
</ul>
</div>
</section>
<section id="example-cont" class="slide level2">
<h2>Example (con’t)</h2>
<ul>
<li><p>Two analysis approaches taken:</p>
<ol type="1">
<li><p><strong>Conditional Approach</strong>: Subsetting the data to domain members only and performing estimation (<span class="alert"><strong>bad!</strong></span>)</p></li>
<li><p><strong>Unconditional Approach:</strong> Appropriately including all sampled units in calculations (<span class="alert2"><strong>good!</strong></span>)</p></li>
</ol></li>
</ul>
<div class="smaller-text">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Unconditional Approach (Correct)</th>
<th>Conditional Approach (Incorrect)</th>
<th>When subsetting, we have…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample Size</td>
<td>68,372</td>
<td>397</td>
<td></td>
</tr>
<tr class="even">
<td>Subpopulation Sample Size</td>
<td>397</td>
<td>397</td>
<td></td>
</tr>
<tr class="odd">
<td>Design Strata</td>
<td>8</td>
<td>8</td>
<td>Correct # strata</td>
</tr>
<tr class="even">
<td>Design Clusters</td>
<td>294</td>
<td>114</td>
<td>Too few PSUs</td>
</tr>
<tr class="odd">
<td>Design DF (# PSUs − # Strata)</td>
<td>286</td>
<td>106</td>
<td>DF too small</td>
</tr>
<tr class="even">
<td>Estimated Percentage</td>
<td>4.8201</td>
<td>4.8201</td>
<td>Correct point estimate</td>
</tr>
<tr class="odd">
<td>Standard Error</td>
<td>1.5904</td>
<td>1.5761</td>
<td>SE too small</td>
</tr>
<tr class="even">
<td>95% CI</td>
<td>(1.6897, 7.9504)</td>
<td>(1.6954, 7.9448)</td>
<td>CI too narrow</td>
</tr>
</tbody>
</table>
<p>Adapted from Table 1 in West et al.&nbsp;(2008)</p>
</div>
</section>
<section id="domain-estimation-in-software" class="slide level2">
<h2>Domain Estimation in Software</h2>
<div class="smaller-text">
<p><strong>Stata:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="co"># estimates just for the domain of interest -- units with DOMAIN not equal to 0</span></span>
<span id="cb1-2"><a></a>svy, <span class="fu">subpop</span>(DOMAIN)<span class="sc">:</span> mean y</span>
<span id="cb1-3"><a></a>svy, <span class="fu">subpop</span>(DOMAIN)<span class="sc">:</span> proportion y</span>
<span id="cb1-4"><a></a></span>
<span id="cb1-5"><a></a><span class="co"># estimates in all domains defined by the unique values of DOMAIN</span></span>
<span id="cb1-6"><a></a>svy<span class="sc">:</span> mean y, <span class="fu">over</span>(DOMAIN)</span>
<span id="cb1-7"><a></a>svy<span class="sc">:</span> proportion y, <span class="fu">over</span>(DOMAIN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p><strong>Stata user warning:</strong> do not use <strong>if</strong> with Stata for domain estimates!</p>
<ul>
<li>This will subset the data (even if you used the <strong>svyset</strong> command on the full dataset)</li>
</ul></li>
</ul>
<p><strong>R:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="co"># estimates just for the domain of interest -- units with DOMAIN = 1/TRUE</span></span>
<span id="cb2-2"><a></a><span class="fu">svymean</span>(<span class="sc">~</span>y, <span class="fu">subset</span>(DESIGN_OBJECT, DOMAIN<span class="sc">==</span><span class="dv">1</span>))</span>
<span id="cb2-3"><a></a></span>
<span id="cb2-4"><a></a><span class="co"># estimates in all domains defined by the unique values of DOMAIN</span></span>
<span id="cb2-5"><a></a><span class="fu">svyby</span>(<span class="sc">~</span>y, <span class="sc">~</span>DOMAIN, DESIGN_OBJECT, svymean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="activity-16.1-part-1" class="slide level2">
<h2>Activity 16.1 (Part 1)</h2>
<p>Domain Estimation and Comparison (Part 1)</p>
</section>
<section id="comparing-domains" class="slide level2">
<h2>Comparing Domains</h2>
<ul>
<li><p>So far in this course we have done a lot of estimating of means and totals and proportions, either for the whole population or (today) for domains</p></li>
<li><p>We have yet to do any formal comparisons – i.e., any hypothesis testing</p></li>
<li><p>If we want to compare two (or more) domains, often we will be using <strong>chi-square tests</strong> – since so much of survey data is <strong>categorical</strong></p></li>
</ul>
<p><br></p>
<ul>
<li><p>I am going to assume you are <span class="alert2">familiar with (and comfortable with) chi-square tests in the context of infinite populations</span> (i.e., what you’ve seen before this class), but stop me if you have questions!</p></li>
<li><p>We will start with an example that illustrates why taking into account the survey design is important when doing tests like a chi-square test</p></li>
</ul>
</section>
<section id="example-households-with-and-without-netflix" class="slide level2">
<h2>Example: Households With and Without Netflix</h2>
<ul>
<li><p>Suppose we have an SRS of <span class="math inline">\(n\)</span> = 500 co-habiting couples from a very large population (i.e., <span class="math inline">\(N\)</span> large enough to be able to ignore the FPC)</p></li>
<li><p>We want to compare two domains: <span class="alert"><strong>People who have Netflix</strong></span> and <span class="alert2"><strong>People who do not have Netflix</strong></span></p></li>
<li><p><span class="alert3">Question: Are people who have Netflix less likely to subscribe to cable TV?</span><br>
(We recognize that no causal link can be made with a cross-sectional survey!)</p></li>
</ul>
<ul>
<li>Data from our SRS of 500 co-habiting couples:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     netflix     Cable TV  No Cable TV         Total
 Has Netflix 57.49% (119) 42.51%  (88) 100.00% (207)
  No Netflix 64.16% (188) 35.84% (105) 100.00% (293)</code></pre>
</div>
</div>
<ul>
<li><p>Resulting estimates:</p>
<ul>
<li><p>119/207 = 57.5% of couples with Netflix have cable TV</p></li>
<li><p>188/293 = 64.2% of couples without Netflix have cable TV</p></li>
</ul></li>
<li><p>Notice that the number of people with (and without) Netflix would be different if we took another sample – random domain sample size!</p></li>
</ul>
</section>
<section id="example-cont-1" class="slide level2">
<h2>Example (con’t)</h2>
<ul>
<li>A chi-square test gives us:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">chisq.test</span>(dat<span class="sc">$</span>netflix, dat<span class="sc">$</span>cable, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  dat$netflix and dat$cable
X-squared = 2.281, df = 1, p-value = 0.131</code></pre>
</div>
</div>
<ul>
<li><p>Conclusion: There is <strong>no evidence of an association</strong> between having Netflix and having cable<br>
(i.e., no evidence that the proportion of people with cable differs for people with/without Netflix)</p></li>
<li><p>Summarize observed association with an <strong>odds ratio (OR)</strong> or <strong>prevalence ratio (PR)</strong>:</p></li>
</ul>
<p><br></p>
<p><br></p>
<p><em>Surveys are (usually) cross-sectional → prefer PR to RR (risk ratio)</em></p>
</section>
<section id="example-cont-2" class="slide level2">
<h2>Example (con’t)</h2>
<ul>
<li><p>Now, suppose we asked <em>both partners</em> about Netflix and cable</p>
<ul>
<li>We’ll have <em>twice as many people</em> (1000 responses, instead of 500), with the same proportions (assuming both partners answered the same), but a different test result:</li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     netflix     Cable TV  No Cable TV         Total
 Has Netflix 57.49% (238) 42.51% (176) 100.00% (414)
  No Netflix 64.16% (376) 35.84% (210) 100.00% (586)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">chisq.test</span>(dat_both<span class="sc">$</span>netflix, dat_both<span class="sc">$</span>cable, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  dat_both$netflix and dat_both$cable
X-squared = 4.5621, df = 1, p-value = 0.03269</code></pre>
</div>
</div>
<ul>
<li><p>Ignoring the clustering has <strong>inflated the test statistic</strong> value and <strong>lowered the p-value</strong></p></li>
<li><p>ICC for this design is very high, in fact it is:</p></li>
<li><p>What is the DEFF for this design?</p></li>
</ul>
</section>
<section id="chi-square-tests-for-complex-survey-data" class="slide level2 pause">
<h2>Chi-Square Tests for Complex Survey Data</h2>
<ul>
<li><p><span class="alert"><strong>Ignoring clustering can <em>inflate</em> test statistics and <em>deflate</em> p-values</strong></span></p>
<ul>
<li><p>Remember, DEFF &gt; 1 for many outcomes in a cluster sample</p></li>
<li><p>A cluster sample of size <span class="math inline">\(n\)</span> provides the same precision as an SRS of size <span class="math inline">\(n\)</span>/DEFF</p>
<ul>
<li>Effective sample size is <em>smaller</em> than <span class="math inline">\(n\)</span></li>
</ul></li>
<li><p>Thus you are <strong>overstating your signficance</strong> (p-value too small)</p></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p><span class="alert2"><strong>Ignoring stratification can <em>deflate</em> test statistics and <em>inflate</em> p-values</strong></span></p>
<ul>
<li><p>Remember, DEFF &lt; 1 for many outcomes in a stratified sample</p></li>
<li><p>A stratified sample of size <span class="math inline">\(n\)</span> provides the same precision as an SRS of size <span class="math inline">\(n\)</span>/DEFF</p>
<ul>
<li>Effective sample size is <em>larger</em> than <span class="math inline">\(n\)</span></li>
</ul></li>
<li><p>Thus you are <strong>being too conservative</strong> (p-value too high)</p></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>The “worse crime” (usually) is ignoring clustering and “overstating” results (inflate Type 1 error)</li>
</ul>
</div>
</section>
<section id="corrections-to-chi-square-tests-for-complex-survey-data" class="slide level2 pause">
<h2>Corrections to Chi-Square Tests for Complex Survey Data</h2>
<ul>
<li>For an <span class="alert">SRS in an infinite population</span>:
<ul>
<li><span class="math inline">\(X^2\)</span> from a chi-square test has a <span class="math inline">\(\chi^2_{(r-1)(c-1)}\)</span> distribution under <span class="math inline">\(H_0\)</span></li>
<li>Thus, <span class="math inline">\(E[X^2] = (r-1)(c-1)\)</span>
<ul>
<li>(the expected value of a chi-square random variable is equal to its DF)</li>
</ul></li>
</ul></li>
<li>For <span class="alert2">complex survey designs</span>:
<ul>
<li><span class="math inline">\(X^2\)</span> from a chi-square test <strong>does not</strong> follow a <span class="math inline">\(\chi^2_{(r-1)(c-1)}\)</span> distribution under <span class="math inline">\(H_0\)</span></li>
</ul></li>
</ul>
<div class="fragment">
<p>
</p><ul>
<li><p>However, we can adjust the test statistic <span class="math inline">\(X^2\)</span> in order to make a <em>rescaled</em> test statistic have an approximately <span class="math inline">\(\chi^2\)</span> distribution</p></li>
<li><p>Two methods used most often (not very creatively named):</p>
<ul>
<li><p><strong>First Order Correction</strong> (also called Rao-Scott first order correction)</p></li>
<li><p><strong>Second Order Correction</strong> (also called Rao-Scott second order correction)</p></li>
</ul></li>
</ul>
</div>
</section>
<section id="option-1-rao-scott-first-order-correction" class="slide level2 pause">
<h2>Option 1: (Rao-Scott) First Order Correction</h2>
<ul>
<li><p><strong>Idea:</strong> Match the <span class="alert"><strong>mean</strong></span> of the test statistic <span class="math inline">\(X^2\)</span> (under the complex design) to the <span class="alert"><strong>mean</strong></span> of a <span class="math inline">\(\chi^2_{(r-1)(c-1)}\)</span> distribution, thus “rescaling” the test statistic</p></li>
<li><p><strong>“First Order”</strong> because we’re rescaling based on the mean</p>
<ol type="1">
<li><p>Calculate <span class="math inline">\(E[X^2]\)</span> = the expected value of <span class="math inline">\(X^2\)</span> for the complex design under <span class="math inline">\(H_0\)</span></p></li>
<li><p>Calculate first order corrected test statistic as &nbsp; <span class="math inline">\(X^2_F = \frac{(r-1)(c-1) X^2}{E[X^2]}\)</span></p></li>
<li><p>Compare <span class="math inline">\(X^2_F\)</span> to a <span class="math inline">\(\chi^2_{(r-1)(c-1)}\)</span> distribution</p>
<ul>
<li>In practice, works better to compare <span class="math inline">\(X^2_F/(r-1)(c-1)\)</span> to an <span class="math inline">\(F\)</span> distribution</li>
</ul></li>
</ol></li>
</ul>
<div class="fragment">
<ul>
<li>Calculation of <span class="math inline">\(E[X^2]\)</span> depends on the cell and marginal probabilities and the DEFF for estimating each of these probabilities (there’s the survey design part!)</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p><span class="alert">Slight problem:</span> we are matching the mean of the distribution – but p-values often come from the tail of the distribution (at least the p-values we care about most!)</p>
<ul>
<li>Variance of <span class="math inline">\(X^2_F\)</span> is actually larger than variance of <span class="math inline">\(\chi^2_{(r-1)(c-1)} \rightarrow\)</span> p-values from <span class="math inline">\(X^2_F\)</span> are slightly smaller than they should be</li>
</ul></li>
</ul>
</div>
</section>
<section id="option-2-rao-scott-second-order-correction" class="slide level2">
<h2>Option 2: (Rao-Scott) Second Order Correction</h2>
<ul>
<li><p><strong>Idea:</strong> Match the <span class="alert2"><strong>mean and variance</strong></span> of the test statistic <span class="math inline">\(X^2\)</span> (under the complex design) to the <span class="alert2"><strong>mean and variance</strong></span> of a <span class="math inline">\(\chi^2_{(r-1)(c-1)}\)</span> distribution, thus “rescaling” the test statistic</p></li>
<li><p><strong>Second Order</strong> because we’re rescaling based on the mean and variance</p>
<ol type="1">
<li><p>Calculate <span class="math inline">\(E[X^2]\)</span> = the expected value of <span class="math inline">\(X^2\)</span> for the complex design under <span class="math inline">\(H_0\)</span></p></li>
<li><p>Calculate <span class="math inline">\(V[X^2]\)</span> = the variance of <span class="math inline">\(X^2\)</span> under <span class="math inline">\(H_0\)</span></p></li>
<li><p>Calculate second order corrected test statistic as &nbsp; <span class="math inline">\(X^2_S = \frac{\nu X^2_F}{(r-1)(c-1)}\)</span> where <span class="math inline">\(\nu = 2\frac{(E[X^2])^2}{V[X^2]}\)</span></p></li>
<li><p>Compare <span class="math inline">\(X^2_F\)</span> to a <span class="math inline">\(\chi^2_{\nu}\)</span> distribution</p>
<ul>
<li>In practice, works better to compare <span class="math inline">\(X^2_S/\nu\)</span> to an <span class="math inline">\(F\)</span> distribution</li>
</ul></li>
</ol>
<ul>
<li>Similar to the Satterthwaite approximation for ANOVA</li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p>Calculation of <span class="math inline">\(V[X^2]\)</span> even more involved than <span class="math inline">\(E[X^2]\)</span>, requires covariance matrix of estimated cell proportions</p></li>
<li><p>For many software packages (Stata, R), the second order correction is the default</p></li>
</ul>
</div>
</section>
<section id="activity-16.1-part-2" class="slide level2">
<h2>Activity 16.1 (Part 2)</h2>
<p>Domain Estimation and Comparison (Part 2)</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>PUBHBIO 7225</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>