<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <title>randridge.github.io – Poststratification</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-ee9811ddca324682092ecb232ae13b5d.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Poststratification</h1>
  <p class="subtitle">PUBHBIO 7225 Lecture 10</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="outline" class="slide level2">
<h2>Outline</h2>
<div class="hidden">

</div>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Topics</strong></p>
<ul>
<li>Adjusting Survey Weights via:
<ul>
<li>Poststratification</li>
<li>Raking</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Activities</strong></p>
<ul>
<li>10.1 Poststratification Weight Adjustments</li>
</ul>
</div></div>
<p><br></p>
<p><strong>Assignments</strong></p>
<ul>
<li>Problem Set 3 due Thursday 10/2/25 11:59pm via Carmen</li>
</ul>
</section>
<section id="limitation-of-stratification-at-the-design-stage" class="slide level2">
<h2>Limitation of Stratification at the Design Stage</h2>
<ul>
<li><p>To use a variable for stratification at the design stage, you must know the value of that variable for all units in the population <strong>before</strong> you conduct the survey</p>
<ul>
<li>In other words, stratification variables must be available on the sampling frame</li>
</ul></li>
<li><p>For some surveys, frame data may be quite limited (especially phone surveys)</p></li>
<li><p>Example: Ohio Medicaid Assessment Survey (OMAS) 2017</p>
<ul>
<li>Phone survey – only geography was available for stratification</li>
<li>Can estimate population-level characteristics (e.g., total number of white people who live in Ohio)</li>
<li>But, we might know the true population totals for these characteristics (e.g., true number of white Ohioans) from another source</li>
<li>Suppose we get an estimate from the data of <span class="math inline">\(\hat{t}_{str} = 8,320,817\)</span> white Ohioans</li>
<li>We know the “true” number of white Ohioans is <span class="math inline">\(t= 7,164,904\)</span><br>
(from American Community Survey 5-year estimates)</li>
</ul></li>
<li><p>How can we reconcile this? Seems like we <strong>oversampled</strong> white people. . .</p></li>
</ul>
</section>
<section id="example-srs-of-osu-students" class="slide level2">
<h2>Example: SRS of OSU Students</h2>
<ul>
<li><p>You are interested in student perception of campus culture at OSU (Columbus Campus)</p></li>
<li><p>There are <span class="math inline">\(N=\)</span> 61443 students on the Columbus campus</p></li>
<li><p>You have access to a sampling frame that contains email addresses, but no additional information on the students (i.e., rank, gender, etc.)</p></li>
<li><p>Thus, you take a <strong>simple random sample</strong> of <span class="math inline">\(n=\)</span> 100 students and send them a survey (cannot stratify on anything b/c your sampling frame doesn’t contain anything useful)</p></li>
<li><p>Probability of selection and sample weight for each of the <span class="math inline">\(n=\)</span> 100 students sampled:</p>
<p><br></p>
<ul>
<li>Probability of selection: <span class="math inline">\(\pi_i =\)</span></li>
</ul>
<p><br></p>
<ul>
<li>Sampling weight: <span class="math inline">\(w_i = 1/\pi_i =\)</span></li>
</ul>
<p><br></p></li>
<li><p>Miraculously, everyone replies (we will get to nonresponse later!)</p></li>
</ul>
</section>
<section id="example-srs-of-osu-students-cont" class="slide level2">
<h2>Example: SRS of OSU Students (con’t)</h2>
<ul>
<li><p>On the survey you ask questions about:</p>
<ul>
<li><p>Level: Undergraduate, Graduate, Professional</p></li>
<li><p>Residency: From Ohio, Not from Ohio</p></li>
</ul></li>
<li><p>Your sample has 67 undergrads, 23 grad students, 10 professional students</p></li>
<li><p>Since an SRS, unweighted proportions are the same as weighted</p></li>
<li><p>Resulting estimates:</p>
<ul>
<li>Undergrads: <span class="math inline">\(\hat{p}_{ug}\)</span> = 67/100 = 0.67</li>
<li>Grad students: <span class="math inline">\(\hat{p}_{grad}\)</span> = 23/100 = 0.23</li>
<li>Professional students: <span class="math inline">\(\hat{p}_{prof}\)</span> = 10/100 = 0.10</li>
</ul></li>
</ul>
</section>
<section id="example-srs-of-osu-students-cont-1" class="slide level2">
<h2>Example: SRS of OSU Students (con’t)</h2>
<ul>
<li><p>But, you know from the OSU Statistical Summary that there are 46815 undergraduates, 11404 graduate students, and 3224 professional students (<a href="https://irp.osu.edu/sites/default/files/documents/2025/03/2024-25-statistical-summary.pdf">Statistical Summary 2024-2025</a>)</p></li>
<li><p>Comparing the proportions:</p></li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Sample</th>
<th></th>
<th style="text-align: right;">Population</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td style="text-align: right;">Count</td>
<td>Proportion</td>
<td style="text-align: right;">Count</td>
<td>Proportion</td>
</tr>
<tr class="even">
<td>Undergraduate</td>
<td style="text-align: right;">67</td>
<td>0.67</td>
<td style="text-align: right;">46815</td>
<td>46815/61443 = 0.762</td>
</tr>
<tr class="odd">
<td>Graduate</td>
<td style="text-align: right;">23</td>
<td>0.23</td>
<td style="text-align: right;">3224</td>
<td>11404/61443 = 0.186</td>
</tr>
<tr class="even">
<td>Professional</td>
<td style="text-align: right;">10</td>
<td>0.1</td>
<td style="text-align: right;">3224</td>
<td>3224/61443 = 0.052</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">100</td>
<td></td>
<td style="text-align: right;">61443</td>
<td></td>
</tr>
</tbody>
</table>
<ul>
<li><p>It seems that grad students and professional students are <strong>over-represented</strong> in your sample, and undergrads are <strong>under-represented</strong></p></li>
<li><p>What can you do about this?</p></li>
</ul>
</section>
<section id="post-survey-weight-adjustments" class="slide level2">
<h2>Post-Survey Weight Adjustments</h2>
<ul>
<li><p>Each student in your sample had a weight of <span class="math inline">\(w_i = N/n =\)</span> 61443/100 = 614.4</p></li>
<li><p>Thus, our estimates of the population size in each group :</p></li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Group</strong></th>
<th style="text-align: center;"><strong># in sample</strong></th>
<th style="text-align: center;"><strong>Weight</strong> <span class="math inline">\(\mathbf{(w_i)}\)</span></th>
<th style="text-align: left;"><strong>Estimated Total</strong> <span class="math inline">\((\hat{t})\)</span></th>
<th style="text-align: center;"><strong>True Total</strong> <span class="math inline">\((t)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Undergrads</td>
<td style="text-align: center;">67</td>
<td style="text-align: center;">614.4</td>
<td style="text-align: left;">67 <span class="math inline">\(\times\)</span> 614.4 = 41166.8</td>
<td style="text-align: center;">46815</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grads</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">614.4</td>
<td style="text-align: left;">23 <span class="math inline">\(\times\)</span> 614.4 = 14131.9</td>
<td style="text-align: center;">11404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Profs</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">614.4</td>
<td style="text-align: left;">10 <span class="math inline">\(\times\)</span> 614.4 = 6144.3</td>
<td style="text-align: center;">3224</td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li><p>Our estimates are not equal to the known truth</p></li>
<li><p>But, we can do something about this!</p></li>
<li><p>We can adjust the weights within each group so that estimated totals equal true totals</p></li>
<li><p>We want to <strong>down-weight</strong> grad students and professionals and <strong>up-weight</strong> undergrads</p></li>
<li><p>This is called <strong>Poststratification</strong></p></li>
</ul>
</section>
<section id="poststratification" class="slide level2">
<h2>Poststratification</h2>
<blockquote>
<p><span class="alert"><strong>Poststratification =</strong></span> dividing the sample into subgroups (post-strata) based on known population characteristics and adjusting the survey weights within those subgroups to match the population totals</p>
</blockquote>
<ul>
<li><p>Steps for poststratification:</p>
<ul>
<li>Divide sampled units into subgroups (post-strata) based on characteristics <strong>measured in the sample</strong></li>
<li>Population size of each subgroup is assumed to be known</li>
<li>Adjust sample weights within each post-stratum so that estimated counts equal the true counts
<ul>
<li>All units within a subgroup have the same adjustment made<br>
(e.g., all up-weighted or down-weighted similarly)</li>
</ul></li>
</ul></li>
</ul>
<p><br></p>
<ul>
<li>Post-stratification <strong>aligns the representation of the poststratification variable(s) to match that of the population</strong></li>
</ul>
</section>
<section id="adjusting-the-weights-for-the-srs-of-osu-students" class="slide level2">
<h2>Adjusting the Weights for the SRS of OSU Students</h2>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Group</strong></th>
<th style="text-align: center;"><strong># in sample</strong></th>
<th style="text-align: center;"><strong>Weight</strong> <span class="math inline">\(\mathbf{(w_i)}\)</span></th>
<th style="text-align: left;"><strong>Estimated Total</strong> <span class="math inline">\((\hat{t})\)</span></th>
<th style="text-align: center;"><strong>True Total</strong> <span class="math inline">\((t)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Undergrads</td>
<td style="text-align: center;">67</td>
<td style="text-align: center;">614.4</td>
<td style="text-align: left;">67 <span class="math inline">\(\times\)</span> 614.4 = 41166.8</td>
<td style="text-align: center;">46815</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grads</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">614.4</td>
<td style="text-align: left;">23 <span class="math inline">\(\times\)</span> 614.4 = 14131.9</td>
<td style="text-align: center;">11404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Profs</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">614.4</td>
<td style="text-align: left;">10 <span class="math inline">\(\times\)</span> 614.4 = 6144.3</td>
<td style="text-align: center;">3224</td>
</tr>
</tbody>
</table>
<ul>
<li>Start with the undergrads – what should the weight be for the 67 undergrads if you want to end up with the true population count as your estimate? (How many units should each of the 67 UGs “represent”?)</li>
</ul>
<p><br> <br></p>
<ul>
<li>What about the grad students and the professional students?</li>
</ul>
</section>
<section id="poststratified-weights" class="slide level2">
<h2>Poststratified Weights</h2>
<ul>
<li><p>Should remind you of stratified sampling – different weight in each (post)stratum – but now the <span class="math inline">\(n_h\)</span> are not fixed in advance so we have added variability</p></li>
<li><p>For unit <span class="math inline">\(j\)</span> in post-stratum <span class="math inline">\(h\)</span>: <span class="math display">\[\begin{aligned}
\text{\textcolor{blue}{Poststratified weight}} &amp;= \text{\textcolor{red}{original weight}} \times \text{\textcolor{purple}{adjustment factor}} &amp; \\
\textcolor{blue}{w_{hj}^{PS}} &amp;= \textcolor{red}{w_{hj}} \times \textcolor{purple}{\frac{\text{Population total in post-stratum}~h}{\text{Estimated total in post-stratum}~h}} \\
&amp; = \textcolor{red}{w_{hj}} \times \textcolor{purple}{\frac{N_h}{\widehat{N}_h}}
\end{aligned}\]</span></p></li>
<li><p>You can poststratify on multiple variables if you know the population totals <strong>in their crosstabulation</strong></p>
<ul>
<li>For example, you need to know level-by-residency totals:
<ul>
<li>Undergraduates from Ohio</li>
<li>Undergraduates not from Ohio</li>
<li>Grad students from Ohio… etc.</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="poststratification-of-the-srs-of-osu-students" class="slide level2">
<h2>Poststratification of the SRS of OSU Students</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Orig.&nbsp;Weight</strong></td>
<td style="text-align: right;"><strong>Est.&nbsp;Total</strong></td>
<td style="text-align: right;"><strong>True Total</strong></td>
<td style="text-align: right;"><strong>Poststratified Weight</strong></td>
</tr>
<tr class="even">
<td><strong>Post-stratum</strong></td>
<td style="text-align: center;"><span class="math inline">\(n_h\)</span></td>
<td style="text-align: center;"><span class="math inline">\(w_{hj}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\widehat{N}_h\)</span></td>
<td style="text-align: right;"><span class="math inline">\(N_h\)</span></td>
<td style="text-align: right;"><span class="math inline">\(w_{hj}^{PS} = w_{hj} \times \frac{N_h}{\widehat{N}_h}\)</span></td>
</tr>
<tr class="odd">
<td>Undergrad</td>
<td style="text-align: center;">67</td>
<td style="text-align: center;">614.4</td>
<td style="text-align: right;">41166.81</td>
<td style="text-align: right;">46815</td>
<td style="text-align: right;">614.4<span class="math inline">\(\times\)</span> 46815 / 41166.81 = 698.7</td>
</tr>
<tr class="even">
<td>Grad</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">614.4</td>
<td style="text-align: right;">14131.89</td>
<td style="text-align: right;">11404</td>
<td style="text-align: right;">614.4<span class="math inline">\(\times\)</span> 11404 / 14131.89 = 495.8</td>
</tr>
<tr class="odd">
<td>Professional</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">614.4</td>
<td style="text-align: right;">6144.3</td>
<td style="text-align: right;">3224</td>
<td style="text-align: right;">614.4<span class="math inline">\(\times\)</span> 3224 / 6144.3 = 322.4</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Notice that the weights went <strong>up</strong> for undergrads, <strong>down</strong> for grad and professional</p></li>
<li><p>These new weights, <span class="math inline">\(w_{hj}^{PS}\)</span>, replace the original weights, <span class="math inline">\(w_{hj}\)</span> for all calculations</p></li>
<li><p>This eﬀectively creates a stratified sample → use stratified sampling formulae for estimates</p>
<ul>
<li>E.g., Overall proportion: <span class="math inline">\(\hat{p}_{PS} = \sum_{h=1}^H \frac{N_h}{N} \hat{p}_h\)</span></li>
</ul></li>
</ul>
</section>
<section id="estimates-after-poststratification" class="slide level2">
<h2>Estimates after Poststratification</h2>
<ul>
<li>For example, estimating the <strong>proportion of students from Ohio</strong>:</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 26%">
<col style="width: 38%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Post-stratum</strong></th>
<th style="text-align: center;"><strong>Sample Proportion from Ohio</strong> <span class="math inline">\(\mathbf{(\hat{p}_h)}\)</span></th>
<th style="text-align: center;"><strong>Stratum Size</strong> <span class="math inline">\(\mathbf{(N_h)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Undergrad <span class="math inline">\((h=1)\)</span></td>
<td style="text-align: center;">49/67 = 0.7313433</td>
<td style="text-align: center;">46815</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grad <span class="math inline">\((h=2)\)</span></td>
<td style="text-align: center;">14/23 = 0.6086957</td>
<td style="text-align: center;">11404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Professional <span class="math inline">\((h=3)\)</span></td>
<td style="text-align: center;">4/10 = 0.4</td>
<td style="text-align: center;">3224</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">67/100 = 0.67</td>
<td style="text-align: center;">61443</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Poststratified</strong> estimate of overall proportion from Ohio: <span class="math display">\[\begin{flalign}
\hat{p}_{PS} &amp;= \sum_{h=1}^H \frac{N_h}{N} \hat{p}_h = \frac{N_1}{N} \hat{p}_1 + \frac{N_1}{N} \hat{p}_1 + \frac{N_3}{N} \hat{p}_3 &amp; \\
&amp;= \frac{\text{46815}}{\text{61443}} \times \text{0.731} + \frac{\text{11404}}{\text{61443}} \times \text{0.609} + \frac{\text{3224}}{\text{61443}} \times \text{0.4} = \textbf{0.691}
\end{flalign}\]</span></li>
<li>Slightly higher than the original estimate of 67% – undergrads were <strong>underrepresented</strong> in the sample, and they are <strong>more likely</strong> to be from Ohio</li>
</ul>
</section>
<section id="estimates-after-poststratification-using-adjusted-weights" class="slide level2">
<h2>Estimates after Poststratification Using Adjusted Weights</h2>
<ul>
<li><p>Let <span class="math inline">\(y_i = \begin{cases} 1 &amp; \text{person $i$ is from Ohio} \\ 0 &amp; \text{person $i$ is NOT from Ohio} \end{cases}\)</span></p></li>
<li><p>Poststratified weights: <span class="math inline">\(w_i^{PS} = \begin{cases} \text{698.7} &amp; \text{Undergrad (stratum 1)} \\ \text{495.8} &amp; \text{Grad (stratum 2)} \\ \text{322.4} &amp; \text{Professional (stratum 3)} \end{cases}\)</span> <span class="math display">\[\begin{aligned}
\hat{t}_{PS} = \sum_{i \in S} w_i^{PS} y_i &amp;= \sum_{h = 1}^{3} \sum_{j \in S_h} w_{hj}^{PS} y_{hj} = \underbrace{\sum_{j \in S_1} \text{698.7} \times y_{1j}}_{\text{stratum 1}} + \underbrace{\sum_{j \in S_2} \text{495.8} \times y_{2j}}_{\text{stratum 2}} + \underbrace{\sum_{j \in S_3} \text{322.4} \times y_{3j}}_{\text{stratum 3}} \\
&amp;= \text{698.7} \times \underbrace{\sum_{j \in S_1} y_{1j}}_{\text{\# from OH}} + \text{495.8} \times \underbrace{\sum_{j \in S_2} y_{2j}}_{\text{\# from OH}} + \text{322.4} \times \underbrace{\sum_{j \in S_3} y_{3j}}_{\text{\# from OH}}\\
&amp; = \text{698.7} \times \text{49} + \text{495.8} \times \text{14} + \text{322.4} \times \text{4} = \text{42469}
\end{aligned}\]</span></p></li>
<li><p>Thus <span class="math inline">\(\hat{p}_{PS} = \frac{\hat{t}_{PS}}{N} = \frac{\text{42469}}{\text{61443}} = \text{0.691}\)</span></p></li>
</ul>
</section>
<section id="why-does-poststratification-work-the-theory" class="slide level2">
<h2>Why Does Poststratification Work?: The Theory</h2>
<ul>
<li><p>Unlike stratification at the design stage, the <span class="math inline">\(n_h\)</span> in poststrata <strong>are random variables</strong></p></li>
<li><p>Take a different SRS and the number in each poststrata will be <strong>different</strong> (unlike fixed sizes of design strata)</p></li>
<li><p>But – the poststratified mean estimate is still an estimator for the true mean <span class="math display">\[\begin{aligned}
E[\bar{y}_{PS}] &amp;= E\left[\sum_{h=1}^H \frac{N_h}{N} \bar{y}_h \right] = E\left[ E\left(\sum_{h=1}^H \frac{N_h}{N} \bar{y}_h \bigg\vert n_1, n_2, \dots, n_h \right) \right]   \qquad \text{\small (condition on fixed poststratum sizes)} \\
&amp;= E\left[ \sum_{h=1}^H \frac{N_h}{N} E\left( \bar{y}_h \bigg\vert n_1, n_2, \dots, n_h \right) \right] = E\left[ \sum_{h=1}^H \frac{N_h}{N} \bar{y}_{hU} \right] = \bar{y}_U
\end{aligned}\]</span><br>
</p></li>
<li><p>So why would we ever stratify at the design stage?</p>
<ul>
<li><p>Technically, the variance of <span class="math inline">\(\bar{y}_{PS}\)</span> is larger than <span class="math inline">\(\bar{y}_{str}\)</span> because the <span class="math inline">\(n_h\)</span> are random</p></li>
<li><p>Also, guard against a fluke “bad sample”</p></li>
</ul></li>
</ul>
</section>
<section id="variance-estimation-after-poststratification-of-an-srs" class="slide level2">
<h2>Variance Estimation after Poststratification (of an SRS)</h2>
<ul>
<li><p>If the strata are fixed at the design stage (<span class="math inline">\(n_h\)</span> are fixed), we have the usual formula: <span class="math inline">\(V(\bar{y}_{str}) = \sum_{h=1}^H \left(\frac{N_h}{N}\right)^2  \left(1-\frac{n_h}{N_h}\right)\frac{S_h^2}{n_h}\)</span></p></li>
<li><p>With poststratification, <span class="math inline">\(n_h\)</span> are random variables and we can do some trickery to get: <span class="math display">\[\begin{aligned}
V(\bar{y}_{PS}) &amp;= E[ V(\bar{y}_{str} | n_1, n_2, \dots, n_h)] + V[ E(\bar{y}_{str} | n_1, n_2, \dots, n_h)] &amp; \\
&amp;= E\left[ \sum_{h=1}^H \left(\frac{N_h}{N}\right)^2  \left(1-\frac{n_h}{N_h}\right)\frac{S_h^2}{n_h}\right] + \underbrace{V(\bar{y}_U)}_{\text{\small (= 0)}} = E\left[\sum_{h=1}^H \left(\frac{N_h}{N}\right)^2  \frac{S_h^2}{n_h} - \sum_{h=1}^H \left(\frac{N_h}{N}\right)^2  \frac{S_h^2}{N_h}\right]\\
&amp;= \sum_{h=1}^H \left(\frac{N_h}{N}\right)^2 S_h^2 E\left(\frac{1}{n_h}\right) - \sum_{h=1}^H \left(\frac{N_h}{N}\right)^2  \frac{S_h^2}{N_h}  \quad (\text{\small only random variable is }n_h)\\
&amp;= \dots \text{using an approximation for } E(1/n_h) \text{ and some algebra}\dots \\
&amp;\approx \underbrace{\sum_{h=1}^H \frac{N_h}{N}\left(1-\frac{n}{N}\right)\frac{S_h^2}{n}}_{\text{variance under proportional allocation!}} + \underbrace{\sum_{h=1}^H \left(1-\frac{N_h}{N} \right) \frac{S_h^2}{n^2}}_{\text{extra variability due to $n_h$ being random}}
\end{aligned}\]</span></p></li>
</ul>
</section>
<section id="variance-estimation-cont" class="slide level2">
<h2>Variance Estimation (con’t)</h2>
<p><span class="math inline">\(\displaystyle V(\bar{y}_{PS}) = \textcolor{red}{\sum_{h=1}^H \frac{N_h}{N}\left(1-\frac{n}{N}\right)\frac{S_h^2}{n}} + \textcolor{blue}{\sum_{h=1}^H \left(1-\frac{N_h}{N} \right) \frac{S_h^2}{n^2}}\)</span></p>
<ul>
<li><p>Notice that the is of order <span class="math inline">\(n^{-2}\)</span> (<span class="math inline">\(n^2\)</span> in denominator)</p></li>
<li><p>Usually the 2nd term is really small compared to the first term</p></li>
<li><p>Thus, variance of the poststratified mean (of an SRS) is usually effectively <strong>the same as variance of the stratified mean under proportional allocation</strong>!</p></li>
<li><p>This holds as long as the total sample size <span class="math inline">\(n\)</span> is “large” (and it is in most surveys)</p></li>
<li><p>Poststratification (or related weight adjustment methods) are <strong>very commonly used</strong> in household surveys</p>
<ul>
<li><p>Often don’t have demographic info on the frame (example: OMAS), or it is limited</p></li>
<li><p>Do have access to population counts of people based on demographics such as age/race groups from the Census or other source</p></li>
<li><p>Thus, use age and race (cross-classified) to post-stratify</p></li>
</ul></li>
<li><p>Importantly – <strong>poststratification can be used with complex survey designs(not just SRS)</strong></p></li>
</ul>
</section>
<section id="activity-9.1" class="slide level2">
<h2>Activity 9.1</h2>
<p>Poststratification</p>
</section>
<section id="post-survey-weight-adjustments-raking" class="slide level2">
<h2>Post-Survey Weight Adjustments: Raking</h2>
<ul>
<li><p>Often we can get the population totals for a set of variables – age, race, etc. – but only the <strong>marginal counts</strong></p>
<ul>
<li>We know the number in each age group, and the number in each race group, but not in groups formed by crossing age and race (e.g., 18-25 year old white individuals, 18-25 year old Black individuals, etc.)</li>
</ul></li>
<li><p>In this case, a method called <strong>raking</strong> can be used to adjust the weights to achieve the correct (true) marginal totals</p>
<ul>
<li><p>You may see raking also referred to as “iterative proportional fitting”</p></li>
<li><p>In <strong>raking</strong> you iteratively adjust the sample weights to match each set of marginal totals, going back and forth between margins (variables) until convergence (until all margins “match” the truth)</p></li>
<li><p>This is easiest seen in an example…</p></li>
</ul></li>
</ul>
</section>
<section id="example-raking" class="slide level2">
<h2>Example: Raking</h2>
<div class="smaller-text">
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<tbody>
<tr class="odd">
<td><strong>MARGINS</strong></td>
<td style="text-align: center;"><strong>Residency</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td><strong>Level</strong></td>
<td style="text-align: center;">OH</td>
<td style="text-align: center;">Non-OH</td>
<td style="text-align: center;">Total</td>
</tr>
<tr class="odd">
<td>Undergrad</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">46815</td>
</tr>
<tr class="even">
<td>Grad</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">11404</td>
</tr>
<tr class="odd">
<td>Professional</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">3224</td>
</tr>
<tr class="even">
<td>Total</td>
<td style="text-align: center;">42191</td>
<td style="text-align: center;">19252</td>
<td style="text-align: center;">61443</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<tbody>
<tr class="odd">
<td><strong>SAMPLE DATA</strong></td>
<td style="text-align: center;"><strong>Residency</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td><strong>Level</strong></td>
<td style="text-align: center;">OH</td>
<td style="text-align: center;">Non-OH</td>
<td style="text-align: center;">Total</td>
</tr>
<tr class="odd">
<td>Undergrad</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">67</td>
</tr>
<tr class="even">
<td>Grad</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="odd">
<td>Professional</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">67</td>
</tr>
<tr class="even">
<td>Total</td>
<td style="text-align: center;">67</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
</div></div>
</div>
<ul>
<li><p>Start with the row variable (<strong>level</strong>), and adjust the sample weights via poststratification</p>
<ul>
<li>Same as when we poststratified by level – new weights for each level<br>
(undergrad: <span class="math inline">\(w_i\)</span> = 698.7; grad: <span class="math inline">\(w_i\)</span> = 495.8; professional: <span class="math inline">\(w_i\)</span> = 322.4)</li>
</ul></li>
<li><p>Now totals for <strong>level</strong> are right – but totals for the other variable (<strong>residency</strong>) are not</p>
<ul>
<li>Ex: Sum of weights for OH = 49 <span class="math inline">\(\times\)</span> 698.7 + 14 <span class="math inline">\(\times\)</span> 495.8 + 4 <span class="math inline">\(\times\)</span> 322.4 = 42469 – but should be 42191</li>
</ul></li>
<li><p>So, adjust the weights via poststratification using the other variable (<strong>residency</strong>)</p>
<!-- -   Example: For OH resident, multiply the (previously adjusted) -->
<!--     weight times 42191/42469 ($= N_h$/$\widehat{N}_h$) --></li>
<li><p>But now the totals for the first variable (<strong>level</strong>) are wrong…so go back and adjust with those margins</p></li>
<li><p>Repeat until weights don’t change (and marginal totals are correct!)</p></li>
</ul>
</section>
<section id="example-raking-cont" class="slide level2">
<h2>Example: Raking (con’t)</h2>
<p>Resulting survey weights for the SRS of OSU students:</p>
<table class="caption-top">
<colgroup>
<col style="width: 35%">
<col style="width: 20%">
<col style="width: 24%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: left;">Sample Count</th>
<th style="text-align: left;">Original Weight</th>
<th style="text-align: left;">Raked Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Undergrad / Ohio</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">614.4</td>
<td style="text-align: left;">694.615</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grad / Ohio</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">614.4</td>
<td style="text-align: left;">491.583</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Professional / Ohio</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">614.4</td>
<td style="text-align: left;">318.189</td>
</tr>
<tr class="even">
<td style="text-align: left;">Undergrad / Not Ohio</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">614.4</td>
<td style="text-align: left;">709.937</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grad / Not Ohio</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">614.4</td>
<td style="text-align: left;">502.427</td>
</tr>
<tr class="even">
<td style="text-align: left;">Professional / Not Ohio</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">614.4</td>
<td style="text-align: left;">325.208</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Notice that now we will get the <strong>correct totals for level and for residency</strong>!</p>
<ul>
<li><p>Ex: Number of students from Ohio = 49 <span class="math inline">\(\times\)</span> 694.615 + 14 <span class="math inline">\(\times\)</span> 491.583 + 4 <span class="math inline">\(\times\)</span> 318.189 = 42191 ✓</p></li>
<li><p>Ex: Number of undergrads = 49 <span class="math inline">\(\times\)</span> 694.615 + 18 <span class="math inline">\(\times\)</span> 709.937 = 46815 ✓</p></li>
</ul></li>
<li><p>But, we are not guaranteed to get the correct level-by-residency totals</p>
<ul>
<li>Ex: Estimated number of undergrads from Ohio = 49 <span class="math inline">\(\times\)</span> 694.615 = 34036 ← <strong>not guaranteed to be right</strong></li>
</ul></li>
</ul>
</section>
<section id="raking-some-properties" class="slide level2">
<h2>Raking: Some Properties</h2>
<p><strong>Pros</strong></p>
<ul>
<li><p>Can be done with more than two variables</p></li>
<li><p>Does not always converge… diagnostics are often used to make sure adjustments are not too severe</p></li>
<li><p>Used extensively in U.S. household surveys where Census or other source can provide high quality totals</p></li>
<li><p>Used even when totals are not technically “known” but rather estimated with high precision – and with higher precision than fully crossed cells (e.g., level-by-residency) that would be needed for poststratification</p></li>
</ul>
<p><strong>Con</strong></p>
<ul>
<li><p>Can cause inflation of variances if variables used for poststratification are not related to the survey outcomes of interest</p>
<ul>
<li>Just like you want to stratify on variable(s) related to your key survey outcomes, you also want to poststratify or rake to variable(s) related to your key survey outcomes</li>
</ul></li>
</ul>
<p>Importantly – <strong>raking can be used with complex survey designs (not just SRS)</strong></p>
</section>
<section id="caveats-for-post-survey-weight-adjustments" class="slide level2">
<h2>Caveats for Post-Survey Weight Adjustments</h2>
<ul>
<li><p>Theoretically, could use a lot of variables for poststratification and raking</p>
<ul>
<li>Problem: Resulting poststrata can end up with small estimated total counts <span class="math inline">\((\widehat{N}_h)\)</span>, which can make the weights highly variable and unstable</li>
</ul></li>
<li><p>Options:</p>
<ul>
<li><p>Collapse categories in the variable(s) used for poststratification/raking (ad hoc solution)</p></li>
<li><p>Use a model-based method that can handle more poststrata/raking variables and ensure groupings are not too small or weight adjustments are not too extreme</p>
<ul>
<li>Example: OMAS uses something called a Generalized Exponential Model (GEM) to simultaneously adjust the weights to a large set of auxiliary variables – basically, super-charged raking that sets bounds on how much weights can be changed</li>
</ul></li>
</ul></li>
<li><p>Poststratification and raking are also commonly used for <strong>nonresponse adjustment</strong> and to <strong>adjust for undercoverage</strong>, so we will come back to them later in the course</p></li>
<li><p>Both poststratification and raking fall under an umbrella method called <strong>weight calibration</strong> – you may see this terminology used to describe your chosen group project surveys</p></li>
</ul>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>PUBHBIO 7225</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>