<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <meta name="author" content="Generative AI acknowledgment: MS Copilot was used to generate alt text for some images">
  <title>randridge.github.io – Cluster Sampling: One-stage with Unequal Size Clusters</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-37dd58ee8260662a2db356013c91c3b1.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><p>Cluster Sampling:<br>
One-stage with Unequal Size Clusters</p></h1>
  <p class="subtitle">PUBHBIO 7225 Lecture 12</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Generative AI acknowledgment: MS Copilot was used to generate alt text for some images 
</div>
</div>
</div>

</section>
<section id="outline" class="slide level2">
<h2>Outline</h2>
<!-- ::: hidden -->
<!-- \newcommand{\fpchpar}{\left(1-\frac{n_h}{N_h}\right)} -->
<!-- \newcommand{\fpcpar}{\left(1-\frac{n}{N}\right)} -->
<!-- ::: -->
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Topics</strong></p>
<ul>
<li>One-stage Cluster Sampling with Unequal Cluster Sizes</li>
<li>Ratio Estimator</li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>Activities</strong></p>
<ul>
<li>12.1 Clusters of Unequal Sizes</li>
</ul>
</div></div>
<p><br></p>
<p><strong>Assignments</strong></p>
<ul>
<li>Peer Evaluation of Problem Set 3 due Tuesday 10/7/25 11:59pm via Carmen</li>
<li>Quiz 3 due Thursday 10/9/2025 11:59pm via Carmen</li>
<li>Group Progress Report due Thursday 10/9/2025 11:59pm via Carmen (only one group member needs to upload this)</li>
</ul>
</section>
<section id="review-of-one-stage-cluster-sampling" class="slide level2">
<h2>Review of One-Stage Cluster Sampling</h2>
<ul>
<li><p><span class="math inline">\(N\)</span> = number of PSUs (clusters) in the <strong>population</strong></p></li>
<li><p><span class="math inline">\(n\)</span> = number of PSUs (clusters) in the <span class="alert"><strong>sample</strong></span></p></li>
<li><p><span class="math inline">\(M_i\)</span> = number of SSUs (e.g., people) in the <span class="math inline">\(i\)</span>th PSU in the <strong>population</strong></p></li>
<li><p><span class="math inline">\(m_i\)</span> = number of SSUs (e.g., people) in the <span class="math inline">\(i\)</span>th PSU in the <span class="alert"><strong>sample</strong></span></p></li>
<li><p><span class="math inline">\(M_0\)</span> = total number of SSUs (e.g., people) in the <strong>population</strong></p></li>
</ul>
<p>For <strong>one-stage cluster sampling</strong>:</p>
<ol type="1">
<li><p>Take an SRS of <span class="math inline">\(n\)</span> PSUs from a population of <span class="math inline">\(N\)</span> PSUs</p></li>
<li><p>Measure <span class="math inline">\(y_{ij}\)</span> for <strong>all</strong> <span class="math inline">\(M_i\)</span> SSUs within the <span class="math inline">\(i\)</span>th sampled PSU</p></li>
</ol>
</section>
<section id="review-of-one-stage-cluster-sampling-cont" class="slide level2">
<h2>Review of One-Stage Cluster Sampling (con’t)</h2>
<p>To estimate the <strong>mean of</strong> <span class="math inline">\(y\)</span> we…</p>
<ol type="1">
<li><p>Calculate the average cluster total across the sampled PSUs: <span class="math inline">\(\displaystyle \bar{t}= \frac{1}{n} \sum_{i\in \mathcal{S}} t_i\)</span></p></li>
<li><p>Multiply average by number of PSUs to get a grand total: <span class="math inline">\(\displaystyle \hat{t}_{clus}= N \bar{t}= \frac{N}{n} \sum_{i\in \mathcal{S}} t_i\)</span></p></li>
<li><p>Divide by the total number of SSUs to get an overall mean: <span class="math inline">\(\displaystyle \hat{\bar{y}}_{clus}= \frac{\hat{t}_{clus}}{M_0} = \frac{N\bar{t}}{M_0}\)</span></p></li>
<li><p>Estimate variance with: <span class="math inline">\(\displaystyle \widehat{V}(\hat{\bar{y}}_{clus}) = \frac{N^2}{M_0^2} \left(1-\frac{n}{N}\right)\frac{s_t^2}{n}\)</span> where <span class="math inline">\(s_t^2=\widehat{V}(t_i)\)</span></p></li>
</ol>
</section>
<section id="in-a-picture" class="slide level2">
<h2>In a Picture</h2>
<div class="columns">
<div class="column" style="width:80%;">
<p><img data-src="./figures/onestage_illustration.png" style="width:100.0%" alt="Diagram illustrating the process of selecting a Simple Random Sample (SRS) from a population of Primary Sampling Units (PSUs) and aggregating data to totals."></p>
</div><div class="column" style="width:20%;">
<ul>
<li><span class="math inline">\(\bar{t}=\)</span></li>
</ul>
<p><br></p>
<p><br></p>
<p><br></p>
<ul>
<li><span class="math inline">\(\hat{t}_{clus}\)</span>=</li>
</ul>
<p><br></p>
<p><br></p>
<p><br></p>
<ul>
<li><span class="math inline">\(\hat{\bar{y}}_{clus} =\)</span></li>
</ul>
</div></div>
</section>
<section id="the-problem-clusters-psus-are-not-usually-equal-sizes" class="slide level2">
<h2>The Problem: Clusters (PSUs) Are Not Usually Equal Sizes</h2>
<ul>
<li><p><span class="alert">Reality:</span> often PSUs are unequal sizes <em>(all the examples from last lecture had</em> <span class="math inline">\(M_i\)</span> the same in all PSUs)</p></li>
<li><p>Really easy to imagine clusters that are <strong>unequal</strong> in size:</p>
<ul>
<li><p>Students within classrooms</p></li>
<li><p>Households within Census tracts</p></li>
<li><p>Patients within hospitals</p></li>
<li><p>Schools within school districts</p></li>
<li><p>Etc.</p></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><span class="alert2"><strong>Good news:</strong></span> the same estimation method <strong>can</strong> be used when <strong>cluster sizes are unequal</strong></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><span class="alert"><strong>Bad news:</strong></span> when PSUs are unequal in size, often the PSU totals <span class="math inline">\((t_i)\)</span> are <span class="alert">highly variable</span>, leading to <span class="alert">large <span class="math inline">\(s_t^2\)</span></span> and thus <span class="alert">large <span class="math inline">\(\widehat{V}(\hat{\bar{y}}_{clus})\)</span></span></li>
</ul>
</div>
</section>
<section id="in-a-picture-1" class="slide level2">
<h2>In a Picture</h2>
<p>Example from last class: sampling rooms, measuring GPA of all students in a room</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>We had all rooms the same size:</strong></p>
<p><img data-src="./figures/onestage_cluster_totals.png" style="width:60.0%" alt="A comparative data visualization consisting of two tables. The left table presents individual student data with three columns: id, room, and gpa. It includes 20 entries grouped by room numbers, showing student IDs and their corresponding GPAs. The right table aggregates this data, displaying the total GPA per room (all rooms have 4 students) with two columns: room and total of GPA. Red arrows visually link each student's GPA in the left table to the corresponding room's total GPA in the right table, illustrating the summation process to show an SRS of totals."></p>
</div><div class="column" style="width:50%;">
<p><strong>What if rooms were different sizes:</strong></p>
<p><img data-src="./figures/onestage_cluster_totals_unequal.png" style="width:60.0%" alt="A comparative data visualization consisting of two tables. The left table presents individual student data with three columns: id, room, and gpa. It includes 20 entries grouped by room numbers, showing student IDs and their corresponding GPAs. The right table aggregates this data, displaying the total GPA per room (with rooms of different sizes) with two columns: room and total of GPA. Red arrows visually link each student's GPA in the left table to the corresponding room's total GPA in the right table, illustrating the summation process to show an SRS of totals."></p>
</div></div>
<ul>
<li>What happens to the <strong>variability</strong> of the <strong>totals</strong> (when rooms are different sizes)?</li>
</ul>
</section>
<section id="example-sampling-school-districts" class="slide level2">
<h2>Example: Sampling School Districts</h2>
<p>Population: <span class="math inline">\(M_0=\)</span> 6194 schools in <span class="math inline">\(N=\)</span> 757 school districts</p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><p>PSU = school district</p></li>
<li><p>SSU = school</p></li>
<li><p><span class="math inline">\(y\)</span> = Academic Performance Index (based on standardized test results)</p></li>
<li><p>True population mean API: <span class="math inline">\(\bar{y}_U =\)</span> 664.7</p></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="PUBHBIO7225_L12_unequal1stageClus_files/figure-revealjs/unnamed-chunk-2-1.png" style="width:70.0%" alt="histogram of API scores, approximately normally distributed with slightly heavy tails"></p>
</figure>
</div>
</div>
</div>
</div></div>
<ul>
<li>Number of SSUs per PSU (schools per district) ranges wildly:</li>
</ul>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1       2       4       8       9     552 </code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="PUBHBIO7225_L12_unequal1stageClus_files/figure-revealjs/unnamed-chunk-4-1.png" alt="histogram of number of SSUs (schools) per PSU (district), showing an extremely right-skewed distribution" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="example-cont" class="slide level2">
<h2>Example (con’t)</h2>
<ul>
<li><p>One-stage cluster sample taken of <span class="math inline">\(n=\)</span> 38 PSUs (districts) – roughly 5% of total</p></li>
<li><p>Result is a total of <strong>246 SSUs</strong></p></li>
</ul>
<div class="columns">
<div class="column" style="width:40%;">
<p>Boxplot of API <span class="math inline">\((y)\)</span> by PSU (for the <strong>sample</strong>):</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="PUBHBIO7225_L12_unequal1stageClus_files/figure-revealjs/unnamed-chunk-6-1.png" alt="histogram of API scores for the sample, approximately normally distributed with slightly heavy tails" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:60%;">
<p>Number of SSUs per PSU <strong>in the sample</strong> has pretty big range:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1       1       3       6      10      36 </code></pre>
</div>
</div>
</div></div>
<ul>
<li>Notice that the one really big PSU didn’t happen to get sampled</li>
</ul>
</section>
<section id="example-estimating-the-mean-api" class="slide level2 pause">
<h2>Example: Estimating the Mean API</h2>
<div class="cell cell-output">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span>dnum, <span class="at">weight =</span> <span class="sc">~</span>wt, <span class="at">fpc =</span> <span class="sc">~</span>popsize, <span class="at">data=</span>samp)</span>
<span id="cb3-2"><a></a><span class="fu">svytotal</span>(<span class="sc">~</span>api00, <span class="at">design =</span> des)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        total     SE
api00 3272511 642857</code></pre>
</div>
</div>
<p>
</p><ol type="1">
<li><p>Estimate of total:</p>
<ul>
<li><span class="math inline">\(\hat{t}_{clus} = \text{3272511}\)</span></li>
</ul></li>
</ol>
<div class="fragment">
<ol start="2" type="1">
<li><p>Estimate of mean:</p>
<ul>
<li><span class="math inline">\(\hat{\bar{y}}_{clus}= \hat{t}_{clus}/M_0 = \text{3272511}/\text{6194} = \text{528.3}\)</span> &nbsp;&nbsp; (<span class="math inline">\(M_0=\)</span> 6194 districts in pop.)</li>
</ul></li>
</ol>
</div>
<div class="fragment">
<ol start="3" type="1">
<li><p>Estimate of variance of the mean:</p>
<ul>
<li><span class="math inline">\(\widehat{V}(\hat{\bar{y}}_{clus}) = \frac{1}{M_0^2}\widehat{V}(\hat{t}_{clus}) = \frac{1}{\text{6194}^2} (\text{642857}^2) = \text{10771.7}\)</span></li>
</ul></li>
</ol>
</div>
<div class="fragment">
<ol start="4" type="1">
<li><p>Estimated SE of the mean: <span class="math inline">\(\widehat{SE}(\hat{\bar{y}}_{clus}) = \sqrt{\text{10771.7}} = \text{103.8}\)</span></p>
<ul>
<li>That is a pretty big standard error! 95% CI = 528.3 <span class="math inline">\(\pm\)</span> 103.8 = (320.8, 735.9)</li>
</ul></li>
</ol>
</div>
</section>
<section id="activity-12.1-part-1" class="slide level2">
<h2>Activity 12.1 (Part 1)</h2>
<p>Clusters of Unequal Sizes (Part 1)</p>
</section>
<section id="our-mean-estimate-the-unbiased-estimator" class="slide level2 pause">
<h2>Our Mean Estimate: The Unbiased Estimator</h2>
<ul>
<li><p>Our mean estimator is: <span class="math inline">\(\displaystyle \hat{\bar{y}}_{clus}=  \frac{N \bar{t}}{M_0}  = \frac{\hat{t}_{clus}}{M_0}\)</span></p></li>
<li><p>Note the denominator: <strong>known</strong> total number of SSUs</p></li>
<li><p>This is called the <span class="alert2"><strong>unbiased estimator of the mean</strong></span>, since it is unbiased for the true population mean (<span class="math inline">\(\bar{y}_U\)</span>)</p>
<ul>
<li><p>We have taken an SRS of PSU totals <span class="math inline">\((t_i)\)</span></p></li>
<li><p>Thus by property of SRS, the estimated total is unbiased: <span class="math inline">\(E[\hat{t}_{clus}] = t_U\)</span></p></li>
<li><p>Thus <span class="math inline">\(E[\hat{\bar{y}}_{clus}] = E[\hat{t}_{clus}/M_0]=E[\hat{t}_{clus}]/M_0 = t_U/M_0 = \bar{y}_U\)</span></p></li>
</ul></li>
<li><p>The <strong>unbiased estimator</strong> can be written in terms of sampling weights: <span class="math inline">\(\displaystyle \hat{\bar{y}}_{clus}= \frac{\sum_{i\in \mathcal{S}} \sum_{j\in \mathcal{S}_i}  w_{ij} y_{ij}}{M_0}\)</span></p>
<ul>
<li>Remember that when an SRS of PSUs is taken, <span class="math inline">\(w_{ij} = N/n\)</span> for all sampled units</li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p><span class="alert">But, what if we don’t know <span class="math inline">\(M_0\)</span>?</span></p>
<ul>
<li>For example, if we only have a list of housing units, not people in the units</li>
</ul></li>
<li><p>We can definitely still estimate the total – but can we still estimate the mean?</p></li>
</ul>
</div>
</section>
<section id="another-way-ratio-estimation" class="slide level2 pause">
<h2>Another Way: Ratio Estimation</h2>
<blockquote>
<p><span class="alert"><strong>Ratio estimator of the mean:</strong></span> <span class="math display">\[\hat{\bar{y}}_r= \frac{\hat{t}_{clus}}{\widehat{M}_0} = \frac{N \bar{t}}{N \hat{\bar{M}}} = \frac{N \frac{1}{n} \sum_{i\in \mathcal{S}} t_i}{N\frac{1}{n} \sum_{i\in \mathcal{S}} M_i}  = \frac{\sum_{i\in \mathcal{S}} t_i}{\sum_{i\in \mathcal{S}} M_i} = \frac{\sum_{i\in \mathcal{S}} M_i \bar{y}_i}{\sum_{i\in \mathcal{S}} M_i}\]</span> where <span class="math inline">\(\hat{\bar{M}}= \frac{1}{n} \sum_{i \in \mathcal{S}} M_i =\)</span> average number of SSUs per PSU (based on sample)</p>
</blockquote>
<ul>
<li>Note the denominator: <span class="alert">estimated</span> total number of SSUs</li>
</ul>
<div class="fragment">
<ul>
<li><p>The <strong>ratio estimator</strong> can also be written in terms of sampling weights: <span class="math inline">\(\displaystyle \hat{\bar{y}}_r= \frac{\hat{t}_{clus}}{\widehat{M}_0} = \frac{\sum_{i\in \mathcal{S}} \sum_{j\in \mathcal{S}_i}  w_{ij} y_{ij}}{\sum_{i\in \mathcal{S}} \sum_{j\in \mathcal{S}_i}  w_{ij} }\)</span></p></li>
<li><p>This estimator can be used <strong>even if you don’t know the true total number of SSUs,</strong> <span class="math inline">\(M_0\)</span></p></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>It is, however, <strong>not unbiased</strong> (<span class="math inline">\(E[\hat{\bar{y}}_r] \ne \bar{y}_U\)</span>) and is a <strong>ratio of two random variables</strong></p>
<ul>
<li>Both the numerator, <span class="math inline">\(\hat{t}_{clus}\)</span>, and denominator, <span class="math inline">\(\widehat{M}_0\)</span>, will be different in another sample</li>
</ul></li>
</ul>
</div>
</section>
<section id="another-way-cont" class="slide level2">
<h2>Another Way (con’t)</h2>
<ul>
<li><p>The bias will be small, however, if the correlation between <span class="math inline">\(M_i\)</span> and <span class="math inline">\(t_i\)</span> is close to 1<br>
<em>(If cluster sizes and cluster totals are highly correlated)</em></p></li>
<li><p>And, this is usually the case!</p></li>
<li><p>The <span class="alert">total for each PSU is usually roughly proportional to the size of the PSU</span></p></li>
</ul>

<img data-src="PUBHBIO7225_L12_unequal1stageClus_files/figure-revealjs/unnamed-chunk-10-1.png" class="quarto-figure quarto-figure-center r-stretch" alt="scatterplot with number of schools on the x-axis and total API on the y-axis, showing essentially a 45 degree line" width="960"><p>
</p><ul>
<li><p><span class="math inline">\(\text{Corr}(t_i,M_i) = \text{0.977}\)</span></p></li>
<li><p>Also think about the dorm room example – the more students in a room, the larger the total GPA will be</p></li>
</ul>
</section>
<section id="example-estimating-the-mean-api-with-ratio-estimator" class="slide level2 pause">
<h2>Example: Estimating the Mean API with Ratio Estimator</h2>
<ul>
<li><p>Hand-calculating the ratio estimator:</p>
<ul>
<li><p>From before, <span class="math inline">\(\hat{t}_{clus} = \text{3272511}\)</span></p></li>
<li><p>Weights for each sampled unit = <span class="math inline">\(\frac{N}{n} = \frac{\text{757}}{\text{38}} = \text{19.92}\)</span></p></li>
<li><p>Sample has 246 schools (SSUs), so sum of weights = <span class="math inline">\(\widehat{M}_0 = \text{246} \times \text{19.92} = \text{4900.58}\)</span></p></li>
</ul></li>
</ul>
<p>
</p><div class="fragment">
<ul>
<li>Ratio estimate of mean API: <span class="math inline">\(\displaystyle \hat{\bar{y}}_r= \frac{\hat{t}_{clus}}{\widehat{M}_0} = \frac{\text{3272511}}{\text{4900.58}} = \text{667.8}\)</span></li>
</ul>
<p>
</p></div>
<div class="fragment">
<ul>
<li>Compare to the unbiased estimator, <span class="math inline">\(\displaystyle \hat{\bar{y}}_{clus} = \frac{\hat{t}_{clus}}{M_0} = \frac{\text{3272511}}{\text{6194}} = \text{528.3}\)</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>For this sample, the ratio estimate of the mean is <span class="alert">larger</span> than the unbiased estimate <span class="alert">for this sample</span> – why?</p>
<ul>
<li><em>Note: this is just true for this sample – ratio estimator could be bigger, could be smaller, depends on the specific sample</em></li>
</ul></li>
</ul>
</div>
</section>
<section id="variance-estimation-for-the-ratio-estimator" class="slide level2 pause">
<h2>Variance Estimation for the Ratio Estimator</h2>
<ul>
<li>Why would we want to use a <strong>biased</strong> estimator, even if the bias is small?</li>
</ul>
<div class="fragment">
<ul>
<li>Because of potentially HUGE gains in efficiency – much smaller variance estimate</li>
</ul>
</div>
<div class="fragment">
<p>
</p><ul>
<li><p>But, it is also a <strong>ratio of two random variables</strong> <span class="math inline">\((\hat{t}_{clus},\widehat{M}_0)\)</span>, thus tricky to deal with</p></li>
<li><p>To calculate its variance we use Taylor series <strong>linearization</strong><sup>1</sup></p></li>
</ul>
</div>
<aside><ol class="aside-footnotes"><li id="fn1"><p>It is important to know this name, <strong>linearization</strong>, but not to understand the technical details</p></li></ol></aside></section>
<section id="what-is-linearization" class="slide level2 pause">
<h2>What is Linearization?</h2>
<ul>
<li><p>We want the variance of a nonlinear function of two random variables: <span class="math inline">\(V(\hat{t}_{clus}/\widehat{M}_0)\)</span></p></li>
<li><p>We cannot “pull apart” this <strong>nonlinear</strong> function with rules that work for sums of random variables, like <span class="math inline">\(V(X+Y) = V(X) + V(Y) + 2\text{Cov}(X,Y)\)</span></p></li>
<li><p>But, if we could <span class="alert"><strong>approximate the nonlinear function with a linear function</strong></span> then we <strong>could</strong> use the rules about sums of random variables</p></li>
</ul>
<p>
</p><div class="fragment">
<ul>
<li><p><strong>Linearization</strong> reduces the nonlinear quantity (the ratio, here) to an approximate linear quantity (an expression involving adding and subtracting random variables – not multiplying or dividing them) by using the linear terms of a Taylor series expansion<sup>1</sup></p></li>
<li><p>Then a variance formula can be constructed using usual rules (and an estimate obtained by plugging in estimates of unknown quantities)</p></li>
</ul>
</div>
<aside><ol class="aside-footnotes"><li id="fn2"><p>Again, math details not important – just the concept</p></li></ol></aside></section>
<section id="linearization-for-the-variance-of-the-ratio-estimator" class="slide level2 pause">
<h2>Linearization for the Variance of the Ratio Estimator</h2>
<ul>
<li><p>For our estimate of the mean, <span class="math inline">\(\hat{\bar{y}}_r\)</span>, the first order Taylor series expansion is: <span class="math display">\[\hat{\bar{y}}_r= \frac{\hat{t}_{clus}}{\widehat{M}_0} \approx \frac{t_U}{M_0} + \frac{1}{M_0}\left(\hat{t}_{clus}- \frac{t_U}{M_0} \widehat{M}_0 \right)\]</span></p></li>
<li><p>The <strong>random variables</strong> are the pieces with <strong>hats</strong></p>
<ul>
<li><p><span class="math inline">\(\hat{t}_{clus}, \widehat{M}_0\)</span> – estimates, which are <span class="alert2"><strong>random variables</strong></span></p></li>
<li><p><span class="math inline">\(t_U, M_0\)</span> – fixed (unknown) quantities (<span class="alert"><strong>constants</strong></span>)</p></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li>So now the rules of variance of a linear combination of random variables can be used: <span class="math display">\[V(\hat{\bar{y}}_r) \approx V\left[\frac{t_U}{M_0} + \frac{1}{M_0}\left(\hat{t}_{clus}- \frac{t_U}{M_0} \widehat{M}_0 \right)\right] = \frac{1}{M_0^2}\left[V(\hat{t}_{clus}) + \frac{t_U^2}{M_0^2} V(\widehat{M}_0) - 2\frac{t_U}{M_0} \text{Cov}(\hat{t}_{clus},\widehat{M}_0) \right]\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>To get the estimated variance, plug in <span class="math inline">\(\hat{t}_{clus}\)</span> and <span class="math inline">\(\widehat{M}_0\)</span> (in place of <span class="math inline">\(t_U\)</span> and <span class="math inline">\(M_0\)</span>) in variance expression above</li>
</ul>
</div>
</section>
<section id="linearization-cont" class="slide level2 pause">
<h2>Linearization (con’t)</h2>
<ul>
<li>Looking closer at this variance expression:</li>
</ul>
<p><span class="math display">\[V(\hat{\bar{y}}_r) \approx \frac{1}{M_0^2}\left[V(\hat{t}_{clus}) + \frac{t_U^2}{M_0^2} V(\widehat{M}_0) - 2\frac{t_U}{M_0} \text{Cov}(\hat{t}_{clus},\widehat{M}_0) \right]\]</span></p>
<ul>
<li><p>If the cluster sizes are all the same size:</p>
<ul>
<li><p><span class="math inline">\(\widehat{M}_0 = M_0\)</span> because every sample of <span class="math inline">\(n\)</span> PSUs contains the same number of SSUs, so <span class="math inline">\(V(\widehat{M}_0) = 0\)</span></p></li>
<li><p><span class="math inline">\(\text{Cov}(\hat{t}_{clus},\widehat{M}_0) = 0\)</span> because <span class="math inline">\(\widehat{M}_0\)</span> is a constant, and the covariance of a random variable with a constant is 0</p></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p>Thus, the linearization variance estimator reduces to: <span class="math inline">\(\displaystyle V(\hat{\bar{y}}_r) = \frac{1}{M_0^2} V(\hat{t}_{clus})\)</span></p></li>
<li><p>This is the variance of the unbiased estimator!</p></li>
<li><p>Software (e.g., Stata, R, SAS) uses the linearization estimator even when the clusters are all the same size</p></li>
<li><p>Linearization is also used for other, complex statistics – such as regression coefficients</p></li>
</ul>
</div>
</section>
<section id="variance-estimation-for-one-stage-cluster-sampling-ratio-estimator" class="slide level2 pause">
<h2>Variance Estimation for One-Stage Cluster Sampling (Ratio Estimator)</h2>
<ul>
<li><p>By plugging in estimates for the quantities in <span class="math inline">\(V(\hat{\bar{y}}_r)\)</span>, for a <strong>one-stage cluster sample</strong> where the <strong>sampling of PSUs is via SRS</strong>, we can <span class="alert">estimate</span> the variance of the (ratio estimator of the) mean with: <span class="math display">\[\widehat{V}(\hat{\bar{y}}_r) = \frac{1}{n \hat{\bar{M}}^2} \left(1-\frac{n}{N}\right)\frac{\sum_{i \in \mathcal{S}} (t_i - M_i\hat{\bar{y}}_r)^2}{n-1} = \frac{1}{n \hat{\bar{M}}^2} \left(1-\frac{n}{N}\right)\frac{\sum_{i \in \mathcal{S}} M_i^2 (\bar{y}_i - \hat{\bar{y}}_r)^2}{n-1}\]</span></p></li>
<li><p>Notable pieces:</p>
<ul>
<li><p><span class="math inline">\(\hat{\bar{M}}= \frac{1}{n} \sum_{i \in \mathcal{S}} M_i =\)</span> average number of SSUs per PSU (based on sample)</p></li>
<li><p>FPC = <span class="math inline">\(\left(1-\frac{n}{N}\right)\)</span> is incorporated <strong>based on number of PSUs sampled</strong></p></li>
<li><p>Piece with the summation looks kind of like a variance of <span class="math inline">\(t_i\)</span></p></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p><strong>Key part:</strong> <span class="math inline">\(\sum_{i \in \mathcal{S}} (t_i - M_i\hat{\bar{y}}_r)^2\)</span><br>
= how far the PSU totals <span class="math inline">\((t_i)\)</span> are from the <span class="alert"><strong>estimated total for each specific PSU</strong> <span class="math inline">\((M_i \hat{\bar{y}}_r)\)</span></span></p>
<ul>
<li><span class="math inline">\(M_i \hat{\bar{y}}_r\)</span> = (size of the PSU) <span class="math inline">\(\times\)</span> (estimated mean) = estimate of the total for that PSU</li>
</ul></li>
</ul>
</div>
</section>
<section id="compare-ratio-estimator-to-unbiased-estimator" class="slide level2 pause">
<h2>Compare Ratio Estimator to Unbiased Estimator</h2>
<ul>
<li><p>Recall the estimated variance of the <strong>unbiased estimator</strong>: <span class="math display">\[\widehat{V}(\hat{\bar{y}}_{clus}) = \frac{N^2}{M_0^2} \left(1-\frac{n}{N}\right)\frac{s_t^2}{n} = \frac{1}{n \bar{M}^2} \left(1-\frac{n}{N}\right)\frac{\sum_{i \in\mathcal{S}_i} (t_i - \bar{t})^2}{n-1}\]</span> (plugging in: <span class="math inline">\(s_t^2 = \frac{1}{n-1}\sum_{i \in\mathcal{S}_i} (t_i - \bar{t})^2\)</span>; <span class="math inline">\(\bar{M}=M_0/N=\)</span> true mean number of SSUs per PSU)</p></li>
<li><p><strong>Key part:</strong> <span class="math inline">\(\sum_{i \in\mathcal{S}_i} (t_i - \bar{t})^2\)</span><br>
= how far the PSU totals <span class="math inline">\((t_i)\)</span> are from the <span class="alert"><strong>estimated mean total across all PSUs</strong> <span class="math inline">\((\bar{t})\)</span></span></p></li>
</ul>
<div class="fragment">
<ul>
<li>Variance of the <strong>ratio estimate</strong> of the mean: <span class="math inline">\(\displaystyle \widehat{V}(\hat{\bar{y}}_r) = \frac{1}{n \hat{\bar{M}}^2} \left(1-\frac{n}{N}\right)\frac{\sum_{i \in \mathcal{S}} (t_i - M_i\hat{\bar{y}_r})^2}{n-1}\)</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>Key differences:</p>
<ul>
<li><p>Ratio estimator uses an <strong>estimate</strong> of the average number of SSUs per PSU <span class="math inline">\((\hat{\bar{M}})\)</span> where the unbiased estimator uses the actual, <strong>true</strong> average <span class="math inline">\((M_0/N)\)</span></p></li>
<li><p>Ratio estimator uses <span class="math inline">\((t_i - M_i\hat{\bar{y}}_r)\)</span> while unbiased estimator uses <span class="math inline">\((t_i-\bar{t})\)</span></p>
<!-- -   These differences will be much smaller for ratio estimator since the size of the PSU $(M_i$) is taken into account! --></li>
</ul></li>
</ul>
</div>
</section>
<section id="visualization" class="slide level2">
<h2>Visualization</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="PUBHBIO7225_L12_unequal1stageClus_files/figure-revealjs/unnamed-chunk-13-1.png" alt="plot with PSU number on the x-axis and total on the y-axis, with a line from each dot (total) to the overall average total, which is shown as a horizontal line of triangles. Some of the distances are very large, some are small." width="960"></p>
</figure>
</div>
</div>
</div>
<div class="smaller-text">
<p>Distance from PSU total <span class="math inline">\(t_i\)</span> to <strong>overall average total</strong>, <span class="math inline">\(\bar{t}\)</span></p>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="PUBHBIO7225_L12_unequal1stageClus_files/figure-revealjs/unnamed-chunk-14-1.png" alt="plot with PSU number on the x-axis and total on the y-axis, with a line from each dot (total) to the estimated total for each PSU, which is shown as a triangle for each PSU. Most of the distances are small." width="960"></p>
</figure>
</div>
</div>
</div>
<div class="smaller-text">
<p>Distance from PSU total <span class="math inline">\(t_i\)</span> to <strong>estimated PSU-specific total</strong>, <span class="math inline">\(M_i \hat{\bar{y}}_r\)</span></p>
</div>
</div></div>
<ul>
<li><p>Think about squaring those distances and summing them… HUGE difference!</p></li>
<li><p>Since the PSU totals are usually correlated with the PSU sizes (no matter what <span class="math inline">\(y\)</span> is!), in general the ratio estimator will have <strong>smaller variance</strong>!</p></li>
</ul>
</section>
<section id="example-ratio-estimator-variance-for-mean-api" class="slide level2">
<h2>Example: Ratio Estimator Variance for Mean API</h2>
<ul>
<li>Ratio estimator for the sample of schools:</li>
</ul>
<div class="cell cell-output">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">svymean</span>(<span class="sc">~</span>api00, <span class="at">design =</span> des)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        mean     SE
api00 667.78 27.859</code></pre>
</div>
</div>
<p>
</p><div class="cell cell-output">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">confint</span>(<span class="fu">svymean</span>(<span class="sc">~</span>api00, <span class="at">design =</span> des))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         2.5 %   97.5 %
api00 613.1775 722.3835</code></pre>
</div>
</div>
<ul>
<li><p>Compare to the unbiased estimator (previously calculated):</p>
<ul>
<li><p><span class="math inline">\(\hat{\bar{y}}_{clus}\)</span> = 528.3</p></li>
<li><p><span class="math inline">\(\widehat{SE}(\hat{\bar{y}}_{clus})\)</span> = 103.8</p></li>
<li><p>95% CI = (320.8, 735.9)</p></li>
</ul></li>
<li><p><strong>HUGE</strong> gain in efficiency with ratio estimator! SE almost 4 times larger for <span class="math inline">\(\hat{\bar{y}}_{clus}\)</span>!</p></li>
</ul>
</section>
<section id="activity-12.1-part-2" class="slide level2">
<h2>Activity 12.1 (Part 2)</h2>
<p>Clusters of Unequal Sizes (Part 2)</p>


</section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>PUBHBIO 7225</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>