<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <title>randridge.github.io – Two-stage Cluster Sampling </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-37dd58ee8260662a2db356013c91c3b1.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><p>Two-stage Cluster Sampling<br>
</p></h1>
  <p class="subtitle">PUBHBIO 7225 Lecture 13</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="outline" class="slide level2">
<h2>Outline</h2>
<div class="hidden">

</div>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Topics</strong></p>
<ul>
<li><p>Two-stage Cluster Sampling</p>
<ul>
<li><p>Unbiased Estimators</p></li>
<li><p>Ratio Estimators</p></li>
<li><p>Sampling Weights</p></li>
<li><p>Variance Estimation</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>Activities</strong></p>
<ul>
<li>13.1 Two-Stage Cluster Sampling</li>
</ul>
</div></div>
<p><strong>Readings</strong></p>
<ul>
<li>Handout on Carmen with mathematical details on variance estimation (OPTIONAL)</li>
</ul>
<p><strong>Assignments</strong></p>
<ul>
<li>Quiz 3 due Thursday 10/9/2025 11:59pm via Carmen</li>
<li>Group Progress Report due Thursday 10/9/2025 11:59pm via Carmen (only one group member needs to upload this)</li>
</ul>
</section>
<section id="two-stage-cluster-sampling" class="slide level2">
<h2>Two-Stage Cluster Sampling</h2>
<ul>
<li><p>In <strong>one-stage</strong> cluster sampling, we sample <strong>all SSUs</strong> within the sampled PSUs</p></li>
<li><p>In <strong>two-stage</strong> cluster sampling, we only sample <strong>some SSUs</strong> within the sampled PSUs</p></li>
<li><p>Why might we do this?</p></li>
</ul>
<div class="fragment">
<ul>
<li><p>SSUs within a cluster may be so similar that measuring all is a waste of resources</p></li>
<li><p>Might be expensive to sample SSUs, so only a subsample is taken for cost reasons</p></li>
<li><p>Might not be practical to sample all SSUs (ex: all people in a household)</p></li>
</ul>
</div>
</section>
<section id="stages-of-two-stage-cluster-sampling" class="slide level2">
<h2>Stages of Two-Stage Cluster Sampling</h2>
<ol type="1">
<li><p>Select an SRS of <span class="math inline">\(n\)</span> PSUs from population of <span class="math inline">\(N\)</span> PSUs</p></li>
<li><p>Select an SRS of <span class="math inline">\(m_i\)</span> SSUs from the <span class="math inline">\(M_i\)</span> SSUs in PSU <span class="math inline">\(i\)</span></p></li>
</ol>
<ul>
<li><p>The extra stage of sampling complicates the notation and estimators</p>
<ul>
<li>Two samples:
<ul>
<li><span class="math inline">\(\mathcal{S}\)</span> = the sample of PSUs</li>
<li><span class="math inline">\(\mathcal{S}_i=\)</span> the sample of SSUs from PSU <span class="math inline">\(i\)</span></li>
</ul></li>
</ul></li>
<li><p>Note that quite often in large-scale surveys something other than SRS is used at the first stage – often it is <strong>probability proportional to size (PPS)</strong> sampling</p></li>
<li><p>We will return to this concept next lecture (but it is exactly what it sounds like!)</p></li>
</ul>
</section>
<section id="two-stages-more-variability-more-choices" class="slide level2 pause">
<h2>Two Stages: More Variability, More Choices</h2>
<blockquote>
<p><strong>More Variability:</strong> Now there is sample-to-sample variability from <strong>both</strong> stages of data collection</p>
</blockquote>
<ul>
<li><p>A different two-stage sample could contain the same or different PSUs</p></li>
<li><p>Even if (some/all) same PSUs are selected, a different set of SSUs could be sampled from those PSUs</p></li>
<li><p>As a result, we should expect two contributions to (“pieces of”) the variance of estimators:</p>
<ul>
<li>(1) variability from sampling PSUs, and (2) variability from sampling SSUs within PSU</li>
</ul></li>
</ul>
<div class="fragment">
<blockquote>
<p><strong>More Design Choices:</strong> Have to decide <span class="alert2">how many SSUs per PSU to sample</span></p>
</blockquote>
<ul>
<li><p>We <span class="alert">do not have to sample the same number of SSUs from each PSU</span></p></li>
<li><p>If an PSU with only 1 SSU is sampled, the only choice is to sample 1 SSU (“all”)</p></li>
<li><p>Unlike stratified sampling, where you need at least 2 units per stratum (to estimate variance), <span class="alert"><strong>you can sample just 1 SSU in a sampled PSU</strong></span> (and often we do!)</p>
<ul>
<li>Ex: PSU = housing unit, SSU = person → can sample just 1 person in a household</li>
</ul></li>
</ul>
</div>
</section>
<section id="example-sampling-school-districts" class="slide level2 pause">
<h2>Example: Sampling School Districts</h2>
<p>Population: <span class="math inline">\(M_0=\)</span> 6194 schools in <span class="math inline">\(N=\)</span> 757 school districts</p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><p>PSU = school district</p></li>
<li><p>SSU = school</p></li>
<li><p><span class="math inline">\(y\)</span> = school’s Academic Performance Index<br>
(based on standardized test results)</p></li>
<li><p>True population mean API: <span class="math inline">\(\bar{y}_U =\)</span> 664.7</p></li>
<li><p>Highly skewed number of SSUs per PSU</p></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="PUBHBIO7225_L13_twoStageCluster_files/figure-revealjs/unnamed-chunk-2-1.png" style="width:100.0%" alt="histogram of number of SSUs (schools) per PSU (district), showing an extremely right-skewed distribution"></p>
</figure>
</div>
</div>
</div>
</div></div>
<div class="fragment">
<p><strong>Two-stage cluster sample taken:</strong></p>
<ul>
<li><p><strong>Stage 1:</strong> <span class="math inline">\(n =\)</span> 38 PSUs (districts) out of <span class="math inline">\(N=\)</span> 757 – roughly 5% of total</p>
<ul>
<li>Selected PSUs have a range of <span class="math inline">\(M_i=\)</span> 1 to 36 SSUs</li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p><strong>Stage 2:</strong> <span class="math inline">\(m_i=\)</span> 2 SSUs (schools) per PSU</p>
<ul>
<li>For PSUs with only 1 SSU, <span class="math inline">\(m_i=M_i=1\)</span> (can only select the 1 school!)</li>
</ul></li>
</ul>
</div>
</section>
<section id="slide-school-sample-figure" class="slide level2">
<h2>Example (con’t)</h2>
<ul>
<li>Result is a total of 65 SSUs (schools)
<ul>
<li>Some sampled PSUs (districts) had only 1 SSU (school)</li>
</ul></li>
<li>API <span class="math inline">\((y)\)</span> by PSU (sampled SSUs only):</li>
</ul>

<img data-src="PUBHBIO7225_L13_twoStageCluster_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center r-stretch" alt="Scatterplot of PSU (district) number on the x-axis and API score (y) on the y-axis. There are 1 or 2 points per PSU, reflecting the sampling of 1 or 2 SSUs per PSU." width="960"><ul>
<li><p>Number of SSUs per PSU is either 1 or 2 (by design)</p></li>
<li><p>We want to use this 2-stage cluster sample to estimate the overall mean API</p></li>
</ul>
</section>
<section id="activity-13.1-part-1" class="slide level2">
<h2>Activity 13.1 (Part 1)</h2>
<p>Two-Stage Cluster Sampling (Part 1)</p>
</section>
<section id="similar-estimation-as-one-stage-cluster-sample" class="slide level2 pause">
<h2>Similar Estimation as One-Stage Cluster Sample</h2>
<ul>
<li><p><strong>One-Stage Cluster Sample:</strong> (SRS of <span class="math inline">\(n\)</span> PSUs out of <span class="math inline">\(N\)</span> total; take all <span class="math inline">\(M_i\)</span> SSUs in the selected PSUs):</p>
<ul>
<li><p>To estimate the mean of <span class="math inline">\(y\)</span> we…</p>
<ul>
<li><p>observe the true <span class="math inline">\(t_i\)</span> (total of <span class="math inline">\(y\)</span> for cluster <span class="math inline">\(i\)</span>) in each sampled PSU,</p></li>
<li><p>calculate the average cluster total across the sampled PSUs <span class="math inline">\((\bar{t})\)</span>,</p></li>
<li><p>multiply this average by the number of PSUs (<span class="math inline">\(N\)</span>) to get a grand total <span class="math inline">\((\hat{t}_{clus})\)</span></p></li>
<li><p>and divide by the total number of SSUs <span class="math inline">\((M_0)\)</span> to get the unbiased estimator <span class="math inline">\((\hat{\bar{y}}_{clus})\)</span></p></li>
<li><p>OR, divide by the estimated total number of SSUs <span class="math inline">\((\widehat{M}_0)\)</span> to get the ratio estimate <span class="math inline">\((\hat{\bar{y}}_r)\)</span></p></li>
</ul></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p>In a <strong>Two-Stage Cluster Sample</strong>, <strong>we don’t observe the true</strong> <span class="math inline">\(\mathbf t_i\)</span> for each sampled PSU</p>
<ul>
<li><p>However, we can <em>estimate</em> the PSU-specific totals because we took an SRS from each PSU!</p></li>
<li><p>Essentially this is the only change to the estimation process – add in a step to estimate the PSU totals <span class="math inline">\((\hat{t}_i)\)</span> and then use them like we used the true totals in one-stage cluster sampling</p></li>
<li><p>In other words, replace <span class="math inline">\(t_i\)</span> with <span class="math inline">\(\hat{t}_i\)</span> above (and <span class="math inline">\(\bar{t}\)</span> with <span class="math inline">\(\bar{\hat{t}}\)</span> )</p></li>
<li><p>Of course, variance estimation is much messier…</p></li>
</ul></li>
</ul>
</div>
</section>
<section id="step-1-cluster-specific-estimates" class="slide level2">
<h2>Step 1: Cluster-Specific Estimates</h2>
<p>Start with <strong>cluster-specific estimates</strong>:</p>
<div class="smaller-text">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Quantity</strong></th>
<th style="text-align: left;"><strong>Estimate</strong></th>
<th style="text-align: left;"><strong>In Words</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PSU Mean (of <span class="math inline">\(y\)</span>)</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \bar{y}_i= \frac{1}{m_i} \sum_{j\in \mathcal{S}_i} y_{ij}\)</span></td>
<td style="text-align: left;">average of <span class="math inline">\(y\)</span> for sampled SSUs in PSU <span class="math inline">\(i\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">PSU Total (of <span class="math inline">\(y\)</span>)</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \hat{t}_i = M_i \bar{y}_i\)</span></td>
<td style="text-align: left;">average of <span class="math inline">\(y\)</span> for sampled SSUs times the total number of SSUs in PSU <span class="math inline">\(i\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Variance of <span class="math inline">\(y\)</span> for SSUs within PSU</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle s_i^2 = \frac{1}{m_i-1} \sum_{j \in \mathcal{S}_i} \left(y_{ij}-  \bar{y}_i\right)^2\)</span></td>
<td style="text-align: left;">variance of <span class="math inline">\(y\)</span> for sampled SSUs in PSU <span class="math inline">\(i\)</span></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><p>These look messy – but are just the SRS formulae applied within each PSU!</p></li>
<li><p>Note that the total, <span class="math inline">\(\hat{t}_i\)</span>, has a “hat” on it (its an estimate) – different from 1-stage sampling</p></li>
<li><p>If we have taken an SRS within PSU, then by properties of SRS, estimates are unbiased:</p>
<ul>
<li><p><span class="math inline">\(E[\bar{y}_i] = \bar{y}_{Ui}\)</span></p></li>
<li><p><span class="math inline">\(E[\hat{t}_i] = t_i\)</span></p></li>
<li><p><span class="math inline">\(E[s_i^2] = S_i^2\)</span></p></li>
</ul></li>
</ul>
</section>
<section id="step-2-overall-estimates" class="slide level2">
<h2>Step 2: Overall Estimates</h2>
<p>Then combine cluster-specific estimates to get <strong>overall estimates</strong>:</p>
<div class="smaller-text">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Quantity</strong></th>
<th style="text-align: left;"><strong>Estimate</strong></th>
<th style="text-align: left;"><strong>In Words</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean PSU Total (of <span class="math inline">\(y\)</span>)</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \bar{\hat{t}} = \frac{1}{n} \sum_{i \in \mathcal{S}} \hat{t}_i\)</span></td>
<td style="text-align: left;">average of estimated PSU totals from sampled PSUs</td>
</tr>
<tr class="even">
<td style="text-align: left;">Overall Total (of <span class="math inline">\(y\)</span>)</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \hat{t}_{clus}= N\bar{\hat{t}}\)</span></td>
<td style="text-align: left;">estimated average PSU total times the number of PSUs (in pop.)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Overall Mean (of <span class="math inline">\(y\)</span>)</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \hat{\bar{y}}_{clus}= \frac{\hat{t}_{clus}}{M_0}\)</span> (unbiased estimator)</td>
<td style="text-align: left;">estimated total divided by <strong>known</strong> total number of SSUs</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle \hat{\bar{y}}_r= \frac{\hat{t}_{clus}}{\widehat{M}_0}\)</span> (ratio estimator)</td>
<td style="text-align: left;">estimated total divided by <strong>estimated</strong> total number of SSUs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Variance of PSU Totals</td>
<td style="text-align: left;"><span class="math inline">\(\displaystyle s^2_t = \frac{1}{n-1} \sum_{i \in \mathcal{S}} \left(\hat{t}_i - \bar{\hat{t}} \right)^2\)</span></td>
<td style="text-align: left;">variance of <span class="math inline">\(\hat{t}_i\)</span> for sampled PSUs</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>Note that these steps look just like the steps for one-stage cluster samples – but with (additional) “hats” on the pieces involving <span class="math inline">\(t\)</span> (e.g., <span class="math inline">\(\hat{t}_i, \bar{\hat{t}}\)</span> )</li>
</ul>
</section>
<section id="steps-combined" class="slide level2">
<h2>Steps, Combined</h2>
<ul>
<li><p>So to estimate the mean of <span class="math inline">\(y\)</span> we…</p>
<ul>
<li><p>calculate the mean of <span class="math inline">\(y\)</span> for each sampled PSU <span class="math inline">\((\bar{y}_i)\)</span>,</p></li>
<li><p>multiply this average by the number of SSUs per PSU (<span class="math inline">\(M_i\)</span>) to get the estimated totals in each PSU <span class="math inline">\((\hat{t}_i)\)</span></p></li>
<li><p>calculate the average of the estimated cluster totals <span class="math inline">\(\hat{t}_i\)</span> across the sampled PSUs <span class="math inline">\((\bar{\hat{t}})\)</span>,</p></li>
<li><p>multiply this average by the number of PSUs (<span class="math inline">\(N\)</span>) to get a grand total <span class="math inline">\((\hat{t}_{clus})\)</span></p></li>
<li><p>and divide by the total number of SSUs <span class="math inline">\((M_0)\)</span> to get the unbiased estimate <span class="math inline">\((\hat{\bar{y}}_{clus})\)</span></p></li>
<li><p>OR, divide by the estimated total number of SSUs <span class="math inline">\((\widehat{M}_0)\)</span> to get the ratio estimate <span class="math inline">\((\hat{\bar{y}}_r)\)</span></p></li>
</ul></li>
</ul>
</section>
<section id="expectation-of-the-estimators" class="slide level2 pause">
<h2>Expectation of the Estimators</h2>
<ul>
<li><p><span class="math inline">\(\hat{t}_{clus}\)</span> is an <strong>unbiased</strong> estimator of the true population total <span class="math inline">\(t_U\)</span> (derivation next slide)</p>
<ul>
<li><span class="math inline">\(E[\hat{t}_{clus}] = t_U\)</span></li>
</ul></li>
<li><p>Thus the <span class="alert2"><strong>unbiased estimator</strong></span> of the mean is an <strong>unbiased</strong> estimator of the true population mean, <span class="math inline">\(\bar{y}_U\)</span></p>
<ul>
<li><span class="math inline">\(E[\hat{\bar{y}}_{clus}] = E[\hat{t}_{clus}/M_0] = E[\hat{t}_{clus}]/M_0 = t_U/M_0 = \bar{y}_U\)</span></li>
</ul></li>
<li><p>But the <span class="alert"><strong>ratio estimate</strong></span> of the mean is <strong>biased</strong>, just like with one-stage cluster sampling</p>
<ul>
<li><p><span class="math inline">\(E[\hat{\bar{y}}_r] = E[\hat{t}_{clus}/\widehat{M}_0] \ne \bar{y}_U\)</span></p></li>
<li><p>However, as in that scenario, the drastic decrease in variance for <span class="math inline">\(\hat{\bar{y}}_r\)</span> outweighs its small bias, making it the preferred estimator</p></li>
</ul></li>
</ul>
<p>
</p><div class="fragment">
<ul>
<li><p>For multi-stage sampling we prove theoretical results by <strong>conditioning on a realized sample</strong> and then taking the expectation – using the property of successive conditioning: <span class="math inline">\(E(A) = E[E(A|B)]\)</span></p></li>
<li><p>Inclusion indicator <span class="math inline">\(Z_i\)</span> (for the <span class="math inline">\(i\)</span>th PSU) is a random variable</p></li>
<li><p>For equal probability sampling of PSUs: <span class="math inline">\(P(Z_i=1) = \pi_i = n/N = E(Z_i) = E(Z_i^2)\)</span></p></li>
</ul>
</div>
</section>
<section id="expectation-of-the-estimators-cont" class="slide level2">
<h2>Expectation of the Estimators (con’t)</h2>
<div class="smaller-text">
<p><span class="math display">\[\begin{aligned}
    E(\hat{t}_{clus}) = E(N\bar{\hat{t}}~) = E \left(N \sum_{i \in \mathcal{S}} \frac{1}{n} \hat{t}_i \right) &amp;= E \left(\sum_{i = 1}^N Z_i \frac{N}{n} \hat{t}_i \right) = E \left[ E \left(\sum_{i = 1}^N Z_i \frac{N}{n}\hat{t}_i  \bigg| Z_1, \dots, Z_N \right) \right] \\
    &amp;= E \left[ \sum_{i = 1}^N Z_i \frac{N}{n} E\left(\hat{t}_i  \bigg| Z_1, \dots, Z_N \right) \right] \\
    &amp;= E \left[ \sum_{i = 1}^N Z_i \frac{N}{n} E\left(\hat{t}_i \right) \right] \quad \text{because } \hat{t}_i \perp (Z_1,\dots,Z_N)^*\\
    &amp;= E \left( \sum_{i = 1}^N Z_i \frac{N}{n} t_i \right) \quad \text{because } E(\hat{t}_i) = t_i \\
    &amp;= \sum_{i = 1}^N E(Z_i) \frac{N}{n} t_i \\
    &amp;= \sum_{i = 1}^N \frac{n}{N} \frac{N}{n} t_i = \sum_{i = 1}^N t_i = t_U \quad \text{unbiased!}
    \end{aligned}\]</span></p>
<p><span class="math display">\[E(\hat{\bar{y}}_{clus})  = E ( \hat{t}_{clus}/ M_0) = E ( \hat{t}_{clus})/M_0 = t_U/M_0 = \bar{y}_U \quad \text{unbiased!}\]</span></p>
<p>*Expected value of the estimated total in PSU <span class="math inline">\(i\)</span> (based on the second stage sampling) is independent of whether or not the PSU is selected into the sample</p>
</div>
</section>
<section id="example-cont" class="slide level2">
<h2>Example (con’t)</h2>
<p><strong>Step 1: Cluster-Specific Estimates:</strong> For each of the <span class="math inline">\(n=\)</span> 38 sampled PSUs (districts):</p>
<div class="smaller-text">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">PSU</th>
<th style="text-align: left;"><span class="math inline">\(M_i\)</span></th>
<th style="text-align: left;"><span class="math inline">\(m_i\)</span></th>
<th style="text-align: left;">SSU values of <span class="math inline">\(y\)</span></th>
<th style="text-align: left;"><span class="math inline">\(\bar{y}_i\)</span></th>
<th style="text-align: left;"><span class="math inline">\(\hat{t}_i = M_i \bar{y}_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">753, 807</td>
<td style="text-align: left;">780</td>
<td style="text-align: left;">10 <span class="math inline">\(\times\)</span> 780 = 7800</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">762, 743</td>
<td style="text-align: left;">752.5</td>
<td style="text-align: left;">10 <span class="math inline">\(\times\)</span> 752.5 = 7525</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">536, 540</td>
<td style="text-align: left;">538</td>
<td style="text-align: left;">19 <span class="math inline">\(\times\)</span> 538 = 10222</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">524</td>
<td style="text-align: left;">524</td>
<td style="text-align: left;">1 <span class="math inline">\(\times\)</span> 524 = 524</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div>
<p><strong>Step 2: Combine to get Overall Estimates:</strong></p>
<ul>
<li><p>Mean PSU Total = <span class="math inline">\(\bar{\hat{t}} = \frac{7800 + 7525 + 10222 + \dots}{38} = 4252.013\)</span></p></li>
<li><p>Overall Estimated Total = <span class="math inline">\(\hat{t}_{clus}= N\bar{\hat{t}} = 757 \times 4252.013 = {3218774}\)</span></p></li>
<li><p>Overall Mean, <span class="alert2"><strong>Unbiased Estimator</strong></span> = <span class="math inline">\(\frac{\hat{t}_{clus}}{M_0} = \frac{{3218773.8}}{6194} = {519.7}\)</span></p></li>
</ul>
<!-- -   Overall Mean, **Ratio Estimator** = -->
<!--     $\frac{\hat{t}_{clus}}{\widehat{M}_0}$ $\leftarrow$ Need estimated -->
<!--     population size, $\widehat{M}_0$ -->
<ul>
<li>For <strong>Ratio Estimator:</strong> Estimated population size = <span class="math inline">\(\widehat{M}_0 = \sum_{i \in \mathcal{S}} \sum_{j \in \mathcal{S}_i} w_{ij}\)</span> = sum of weights (sampled SSUs)</li>
</ul>
</section>
<section id="sampling-weights-for-two-stage-cluster-samples" class="slide level2">
<h2>Sampling Weights for Two-Stage Cluster Samples</h2>
<ul>
<li>For two-stage cluster sampling with <strong>SRS</strong> at first and second stage:</li>
</ul>
<blockquote>
<p><span class="alert2"><strong>Sample weight for sampled SSU</strong> <span class="math inline">\(j\)</span> <strong>in PSU</strong> <span class="math inline">\(i\)</span></span>: &nbsp; <span class="math inline">\(\displaystyle w_{ij} = \frac{1}{\pi_{ij}} = \frac{N}{n} \frac{M_i}{m_i}\)</span></p>
</blockquote>
<ul>
<li><p>Intuition:</p>
<ul>
<li><p>Each sampled PSU “represents” <span class="math inline">\(\frac{N}{n}\)</span> PSUs</p></li>
<li><p>And within a PSU each sampled SSU “represents” <span class="math inline">\(\frac{M_i}{m_i}\)</span> SSUs</p></li>
<li><p>So in total a sampled SSU “represents” <span class="math inline">\(\frac{N}{n} \times \frac{M_i}{m_i}\)</span> SSUs</p></li>
</ul></li>
<li><p>Weight is the inverse of the probability of selection:</p>
<p><span class="math display">\[\begin{align}
\pi_{ij} &amp;= P(\text{SSU $j$ of PSU $i$ in sample}) = P(\text{SSU $j$ selected}|\text{PSU $i$ selected}) \times P(\text{PSU $i$ selected})\\
&amp;= \frac{m_i}{M_i} \times \frac{n}{N} = \frac{n}{N}\frac{m_i}{M_i}
\end{align}\]</span></p></li>
</ul>
</section>
<section id="example-cont-1" class="slide level2">
<h2>Example (con’t)</h2>
<ul>
<li><p>To get the ratio estimator, we need the estimated population size:</p>
<ul>
<li><span class="math inline">\(\widehat{M}_0 =  \sum_{i \in \mathcal{S}} \sum_{j \in \mathcal{S}_i} w_{ij}\)</span> = sum of weights, sampled SSUs = 4900.579 (from software)<sup>1</sup></li>
</ul></li>
<li><p>Overall Mean, <span class="alert"><strong>Ratio Estimator</strong></span> = <span class="math inline">\(\displaystyle \frac{\hat{t}_{clus}}{\widehat{M}_0} = \frac{3218773.8}{4900.6} = 656.8\)</span></p></li>
<li><p>We can also write estimates in terms of <strong>weights</strong> (that’s how software is calculating these!)</p>
<ul>
<li><p><span class="math inline">\(\displaystyle \hat{t}_{clus}= \sum_{i \in \mathcal{S}} \sum_{j \in \mathcal{S}_i} w_{ij} y_{ij}\)</span> = weight <span class="math inline">\(\times\)</span> y, added up for all sampled SSUs</p></li>
<li><p><span class="math inline">\(\displaystyle \hat{\bar{y}}_r= \frac{\sum_{i \in \mathcal{S}} \sum_{j \in \mathcal{S}_i} w_{ij} y_{ij}}{\sum_{i \in \mathcal{S}} \sum_{j \in \mathcal{S}_i} w_{ij}} = \frac{\text{ weight $\times$ y, added up for all sampled SSUs}}{\text{sum of weights for all sampled SSUs}}\)</span></p></li>
</ul></li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn1"><p>You can hand-calculate <span class="math inline">\(\widehat{M}_0\)</span> as <span class="math inline">\(\widehat{M}_0 = N \hat{\bar{M}}= N \frac{1}{n} \sum_{i \in S} M_i\)</span> if you wanted to, but do you really want to?</p></li></ol></aside></section>
<section id="epsem-sampling" class="slide level2 pause">
<h2>EPSEM Sampling</h2>
<ul>
<li>In the schools example, the sampling weights <strong>differed</strong> across the 65 sampled SSUs:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  19.92   19.92   39.84   75.39   99.61  358.58 </code></pre>
</div>
</div>
<p>
</p><ul>
<li>Can a two-stage cluster sample be EPSEM (have all sampling weights <strong>equal</strong>)?</li>
</ul>
<div class="fragment">
<ul>
<li>Q: When will <span class="math inline">\(\frac{n}{N}\frac{m_i}{M_i}\)</span> be the same for all PSUs? (for all <span class="math inline">\(i\)</span>)</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>A: When <span class="math inline">\(\frac{m_i}{M_i}\)</span> is the same for all PSUs (for all <span class="math inline">\(i\)</span>)!</p>
<ul>
<li>In other words, when the same <strong>proportion</strong> of SSUs are sampled from each PSU</li>
</ul></li>
</ul>
<p>
</p></div>
<div class="fragment">
<ul>
<li>A two-stage cluster sample (with SRS at the first stage) is only <strong>self-weighting (EPSEM)</strong> if <span class="alert">more SSUs are selected from the larger PSUs</span> (kind of like proportional allocation to strata)</li>
</ul>
</div>
</section>
<section id="activity-13.1-part-2" class="slide level2">
<h2>Activity 13.1 (Part 2)</h2>
<p>Two-Stage Cluster Sampling (Part 2)</p>
</section>
<section id="why-we-focus-on-estimating-the-total" class="slide level2">
<h2>Why We Focus on Estimating the Total</h2>
<ul>
<li><p>We will spend a bit of time calculating the <strong>variance of the estimated total</strong> (and how to estimate it)</p></li>
<li><p>But – our main interest is often <strong>not</strong> in the totals!</p>
<ul>
<li>Possible exception: estimating the number of people with a condition</li>
</ul></li>
<li><p>So why do we focus on the total?</p></li>
</ul>
<p>
</p><div class="fragment">
<ul>
<li><p>Nearly every quantity we want to estimate can be written as a function of <strong>totals</strong></p></li>
<li><p>If we can write the quantity in terms of totals, we can use <strong>linearization</strong> to estimate its variance – like we did with the ratio estimate of the mean in 1-stage cluster sampling</p></li>
<li><p>Linearization can be used for a wide range of estimates:</p>
<ul>
<li><p>Means (ratio estimator)</p></li>
<li><p>Domain (subgroup) estimates</p></li>
<li><p>Linear regression coefficients</p></li>
<li><p>Logistic regression coefficients</p></li>
<li><p>etc.</p></li>
</ul></li>
</ul>
</div>
</section>
<section id="variance-estimation-for-the-estimated-total" class="slide level2">
<h2>Variance Estimation for the Estimated Total</h2>
<ul>
<li><p>As it turns out, <span class="math inline">\(V(\hat{t}_{clus})\)</span> under two-stage cluster sampling is equal to:</p>
<ul>
<li><p>the variance under one-stage cluster sampling, <strong>plus</strong></p></li>
<li><p>an extra term to account for the fact that we are <strong>estimating</strong> the <span class="math inline">\(\hat{t}_i\)</span><br>
(as opposed to directly observing the true <span class="math inline">\(t_i\)</span> in one-stage cluster sampling)</p></li>
</ul></li>
<li><p>True (theoretical) variance of the estimated total<sup>1</sup>: <span class="math display">\[V(\hat{t}_{clus}) = \underbrace{N^2 \left(1-\frac{n}{N}\right)\frac{S^2_t}{n}}_{V_{stage1}} + \underbrace{\frac{N}{n} \sum_{i=1}^N M_i^2 \left(1-\frac{m_i}{M_i}\right) \frac{S_i^2}{m_i}}_{V_{stage2}}\]</span></p>
<p><span class="math inline">\(S^2_t\)</span> = true (population) variance of the PSU totals, <span class="math inline">\(t_i\)</span><br>
<span class="math inline">\(S_i^2\)</span> = true variance of the <span class="math inline">\(y_{ij}\)</span> within PSU <span class="math inline">\(i\)</span></p></li>
<li><p>Note that both these pieces look like SRS formulae – we take an SRS at each stage.</p></li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn2"><p>For derivation, see handout on Carmen</p></li></ol></aside></section>
<section id="variance-estimation-for-the-estimated-total-cont" class="slide level2">
<h2>Variance Estimation for the Estimated Total (con’t)</h2>
<div class="smaller-text">
<ul>
<li>Replacing the unknown variances <span class="math inline">\(S_t^2\)</span> and <span class="math inline">\(S_i^2\)</span> with their sample estimates gives us:</li>
</ul>
<p><span class="math display">\[\widehat{V}(\hat{t}_{clus}) = \underbrace{N^2 \left(1-\frac{n}{N}\right)\frac{s^2_t}{n}}_{\widehat{V}_{stage1}} + \underbrace{\frac{N}{n} \sum_{i \in \mathcal{S}} \left(1-\frac{m_i}{M_i}\right)M_i^2 \frac{s_i^2}{m_i}}_{\widehat{V}_{stage2}}\]</span></p>
<ul>
<li><p><span class="math inline">\(\widehat{V}_{stage1}\)</span> = variability from sampling at the first stage (PSUs)</p>
<ul>
<li>Same as the variance formula for one-stage cluster sampling!</li>
</ul></li>
<li><p><span class="math inline">\(\widehat{V}_{stage2}\)</span> = added variability from sampling at the second stage (SSUs within PSUs)</p>
<ul>
<li>Note that if all SSUs are selected (as in one-stage cluster sampling), <span class="math inline">\(m_i=M_i\)</span> and <span class="math inline">\(\widehat{V}_{stage2}=0\)</span></li>
</ul></li>
<li><p>In many (most) situations, when <span class="math inline">\(N\)</span> is large (and FPC small), <span class="math inline">\(\widehat{V}_{stage1} &gt;&gt; \widehat{V}_{stage2}\)</span></p>
<ul>
<li><p>Variance of the <span class="math inline">\(\hat{t}_i\)</span> can be very large – affected by differences in cluster sizes <span class="math inline">\((M_i)\)</span> and by differences in cluster means <span class="math inline">\((\bar{y}_i)\)</span></p></li>
<li><p>Even if clusters have similar means, different sizes will lead to stage one piece of variance dominating second stage piece</p></li>
</ul></li>
<li><p>If <span class="math inline">\(N\)</span> is large then <span class="math inline">\(\widehat{V}_{stage1}\)</span> is <strong>approximately unbiased</strong> for the true variance, <span class="math inline">\(V(\hat{t}_{clus})\)</span> <sup>1</sup></p></li>
</ul>
</div>
<aside><ol class="aside-footnotes"><li id="fn3"><p>See math details in handout on Carmen if interested.</p></li></ol></aside></section>
<section id="variance-estimation-in-software" class="slide level2 pause">
<h2>Variance Estimation in Software</h2>
<ul>
<li><p>Many software packages simplify calculations by only using <span class="math inline">\(\widehat{V}_{stage1}\)</span></p>
<ul>
<li><span class="math inline">\(\widehat{V}_{stage1}\)</span> is “close enough” to the true variance of the total, since it dominates <span class="math inline">\(\widehat{V}_{stage2}\)</span></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li><p>Might not be able to calculate <span class="math inline">\(\widehat{V}_{stage2}\)</span> because:</p>
<ul>
<li><p>You don’t have the PSU sizes <span class="math inline">\((M_i)\)</span> for sampled PSUs</p>
<ul>
<li>The people who created the dataset had to have PSU sizes (to calculate weights!), but they may not be provided to the end user for publicly available datasets</li>
</ul></li>
<li><p>You might have sampled only 1 SSU per PSU, so cannot calculate <span class="math inline">\(s_i^2\)</span> (within-PSU variance of the SSUs)</p>
<ul>
<li>Very common design when sampling people within households</li>
</ul></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>If the software is ignoring the second stage variance <span class="math inline">\((V_{stage2})\)</span> then you only have to tell it about the PSUs (i.e., don’t need to tell it the <span class="math inline">\(M_i\)</span> or an identifier for the SSUs)</p></li>
<li><p>This is sometimes referred to as an <strong>ultimate PSU analysis</strong></p>
<!-- -   This approach is usually used in complex designs with more than -->
<!--     two stages -->
<ul>
<li><em>It’s still a two-stage design, you’re just ignoring the second stage of sampling when approximating the variance. Sampling weights still need to be constructed accounting for the multiple stages.</em></li>
</ul></li>
</ul>
</div>
</section>
<section id="example-cont-2" class="slide level2">
<h2>Example (con’t)</h2>
<p><span class="alert3"><strong>Estimator of the Total</strong></span></p>
<ul>
<li>Analysis including information about both stages of sampling</li>
</ul>
<div class="cell cell-output">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a>des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span>dnum <span class="sc">+</span> snum, <span class="at">weight =</span> <span class="sc">~</span>wt, <span class="at">fpc =</span> <span class="sc">~</span>N <span class="sc">+</span> Mi, <span class="at">data=</span>samp)</span>
<span id="cb2-2"><a></a><span class="fu">svytotal</span>(<span class="sc">~</span>api00, <span class="at">design =</span> des)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        total     SE
api00 3218774 612674</code></pre>
</div>
</div>
<ul>
<li>Analysis ignoring second stage of sampling (“ultimate PSU analysis”)</li>
</ul>
<div class="cell cell-output">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>des_ign <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span>dnum, <span class="at">weight =</span> <span class="sc">~</span>wt, <span class="at">fpc =</span> <span class="sc">~</span>N, <span class="at">data=</span>samp)</span>
<span id="cb4-2"><a></a><span class="fu">svytotal</span>(<span class="sc">~</span>api00, <span class="at">design =</span> des_ign)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        total     SE
api00 3218774 612593</code></pre>
</div>
</div>
<ul>
<li><p>Point estimates <strong>identical</strong></p></li>
<li><p>Standard error estimates <strong>very similar</strong></p>
<ul>
<li>Most variability is from sampling PSUs (not sampling SSUs within PSUs)</li>
</ul></li>
</ul>
</section>
<section id="variance-estimation-for-the-ratio-estimator" class="slide level2">
<h2>Variance Estimation for the Ratio Estimator</h2>
<ul>
<li><p>For the <span class="alert2"><strong>unbiased estimator</strong></span>, since <span class="math inline">\(M_0\)</span> is a constant, we have <span class="math inline">\(V(\hat{\bar{y}}_{clus}) = \frac{1}{M_0^2} V(\hat{t}_{clus})\)</span></p></li>
<li><p>But we know from 1-stage cluster sampling that we can do better (smaller variance)</p></li>
<li><p>We usually use the <span class="alert"><strong>ratio estimator of the mean</strong></span> for 2-stage cluster sampling: <span class="math inline">\(\displaystyle \hat{\bar{y}}_r= \frac{\hat{t}_{clus}}{\widehat{M}_0}\)</span></p>
<ul>
<li><p>Same as one-stage cluster sampling with unequal cluster sizes</p></li>
<li><p><strong>Linearization</strong> is again used to calculate the theoretical variance, <span class="math inline">\(V(\hat{\bar{y}}_r)\)</span></p>
<ul>
<li><p>We can use the same general result from last time (1-stage cluster sampling): <span class="math display">\[V(\hat{\bar{y}}_r) \approx \frac{1}{M_0^2}\left[V(\hat{t}_{clus}) + \frac{t_U^2}{M_0^2} V(\widehat{M}_0) - 2\frac{t_U}{M_0} \text{Cov}(\hat{t}_{clus},\widehat{M}_0) \right]\]</span></p></li>
<li><p>We just now have a different expression for <span class="math inline">\(V(\hat{t}_{clus})\)</span> because of the 2-stage sampling</p></li>
</ul></li>
<li><p>As we just discussed, often <span class="math inline">\(V(\hat{t}_{clus})\)</span> is approximated by only the stage 1 variance</p></li>
</ul></li>
</ul>
</section>
<section id="variance-estimation-for-the-ratio-estimator-cont" class="slide level2">
<h2>Variance Estimation for the Ratio Estimator (con’t)</h2>
<ul>
<li><p>Variance Estimator: <span class="math display">\[\widehat{V}(\hat{\bar{y}}_r) = \underbrace{\frac{1}{n \hat{\bar{M}}^2} \left(1-\frac{n}{N}\right)\frac{\sum_{i \in \mathcal{S}} (\hat{t}_i - M_i\hat{\bar{y}}_r)^2}{n-1}}_{\widehat{V}_{stage1}} + \underbrace{\frac{1}{nN\hat{\bar{M}}^2} \sum_{i \in \mathcal{S}}M_i^2 \left(1-\frac{m_i}{M_i}\right) \frac{s_i^2}{m_i} }_{\widehat{V}_{stage2}}\]</span></p></li>
<li><p>The first piece, <span class="math inline">\(\widehat{V}_{stage1}\)</span>, is almost the same as 1-stage cluster sampling</p>
<ul>
<li><p>Only difference is the estimated PSU total <span class="math inline">\(\hat{t}_i\)</span> in place of true PSU total <span class="math inline">\(t_i\)</span></p></li>
<li><p>Uses the variability of the estimated PSU totals <span class="math inline">\((\hat{t}_i)\)</span> around a PSU-specific estimated total <span class="math inline">\((M_i\hat{\bar{y}}_r)\)</span>, instead of the (estimated) overall average <span class="math inline">\((\bar{\hat{t}})\)</span> – thus has lower variance than unbiased estimator</p></li>
</ul></li>
<li><p>As with the variance of <span class="math inline">\(\hat{t}_{clus}\)</span>, the second term <span class="math inline">\(\widehat{V}_{stage2}\)</span> is usually very small compared to the first term</p>
<ul>
<li>Thus, we often only calculate the first term, <span class="math inline">\(\widehat{V}_{stage1}\)</span> (“ultimate PSU analysis”)</li>
</ul></li>
</ul>
</section>
<section id="example-cont-3" class="slide level2">
<h2>Example (con’t)</h2>
<p><span class="alert2"><strong>Ratio Estimator of the Mean</strong></span></p>
<ul>
<li>Analysis including information about both stages of sampling</li>
</ul>
<div class="cell cell-output">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span>dnum <span class="sc">+</span> snum, <span class="at">weight =</span> <span class="sc">~</span>wt, <span class="at">fpc =</span> <span class="sc">~</span>N <span class="sc">+</span> Mi, <span class="at">data=</span>samp)</span>
<span id="cb6-2"><a></a><span class="fu">svymean</span>(<span class="sc">~</span>api00, <span class="at">design =</span> des)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        mean     SE
api00 656.82 32.651</code></pre>
</div>
</div>
<ul>
<li>Analysis ignoring second stage of sampling (“ultimate PSU analysis”)</li>
</ul>
<div class="cell cell-output">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>des_ign <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span>dnum, <span class="at">weight =</span> <span class="sc">~</span>wt, <span class="at">fpc =</span> <span class="sc">~</span>N, <span class="at">data=</span>samp)</span>
<span id="cb8-2"><a></a><span class="fu">svymean</span>(<span class="sc">~</span>api00, <span class="at">design =</span> des_ign)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        mean     SE
api00 656.82 32.587</code></pre>
</div>
</div>
<ul>
<li><p>Point estimates <strong>identical</strong></p></li>
<li><p>Standard error estimates <strong>very similar</strong></p>
<ul>
<li>Most variability is from sampling PSUs (not sampling SSUs within PSUs) <a href="#/slide-school-sample-figure">(Look back at plot of API)</a></li>
</ul></li>
</ul>
</section>
<section id="example-cont-4" class="slide level2">
<h2>Example (con’t)</h2>
<p><span class="alert"><strong>Unbiased Estimator of the Mean</strong></span></p>
<ul>
<li><p><strong>With</strong> Second Stage Variance:</p>
<ul>
<li><p><span class="math inline">\(\widehat{V}(\hat{\bar{y}}_{clus}) = \frac{1}{M_0} \widehat{V}(\hat{t}_{clus}) = \frac{1}{6194} (612674^2) = 60{,}602{,}104\)</span></p></li>
<li><p><span class="math inline">\(\widehat{SE}(\hat{\bar{y}}_{clus}) = \sqrt{\widehat{V}(\hat{\bar{y}}_{clus})} = \sqrt{60{,}602{,}104} = {7{,}785}\)</span></p></li>
<li><p>Compare to <span class="math inline">\(\widehat{SE}(\hat{\bar{y}}_r) = {32.65}\)</span></p></li>
</ul></li>
<li><p><strong>Without</strong> Second Stage Variance:</p>
<ul>
<li><p><span class="math inline">\(\widehat{V}(\hat{\bar{y}}_{clus}) = \frac{1}{M_0} \widehat{V}(\hat{t}_{clus}) = \frac{1}{6194} (612593^2) = 60{,}586{,}081\)</span></p></li>
<li><p><span class="math inline">\(\widehat{SE}(\hat{\bar{y}}_{clus}) = \sqrt{\widehat{V}(\hat{\bar{y}}_{clus})} = \sqrt{60{,}586{,}081} = {7{,}784}\)</span></p></li>
<li><p>Compare to <span class="math inline">\(\widehat{SE}(\hat{\bar{y}}_r) = {32.59}\)</span></p></li>
</ul></li>
<li><p>Ratio estimator has <strong>much</strong> smaller SEs!</p></li>
<li><p>SE is over 200 times larger for unbiased estimator!!</p></li>
</ul>
</section>
<section id="activity-13.1-part-3" class="slide level2">
<h2>Activity 13.1 (Part 3)</h2>
<p>Two-Stage Cluster Sampling (Part 3)</p>
</section>
<section id="a-note-on-notation-for-variance-of-ratio-estimator" class="slide level2">
<h2>A Note on Notation for Variance of Ratio Estimator</h2>
<ul>
<li><p>We have the variance estimator for the ratio estimator for 2-stage cluster sampling: <span class="math display">\[\widehat{V}(\hat{\bar{y}}_r) = \frac{1}{n \hat{\bar{M}}^2} \left(1-\frac{n}{N}\right)\frac{\sum_{i \in \mathcal{S}} (\hat{t}_i - M_i\hat{\bar{y}}_r)^2}{n-1} + \frac{1}{nN\hat{\bar{M}}^2} \sum_{i \in \mathcal{S}}M_i^2 \left(1-\frac{m_i}{M_i}\right) \frac{s_i^2}{m_i}\]</span></p></li>
<li><p>We can also write that first stage piece as:</p></li>
</ul>
<p><span class="math display">\[\widehat{V}_{stage1}(\hat{\bar{y}}_r) = \frac{1}{\hat{\bar{M}}^2} \left(1-\frac{n}{N}\right)\frac{{\sum_{i \in \mathcal{S}} (\hat{t}_i - M_i\hat{\bar{y}}_r)^2}}{n{(n-1)}} = \frac{1}{\hat{\bar{M}}^2} \left(1-\frac{n}{N}\right)\frac{{s_r^2}}{n}\]</span></p>
<ul>
<li><p><span class="math inline">\({s_r^2} = \frac{1}{n-1} \sum_{i \in \mathcal{S}} (\hat{t}_i - M_i\hat{\bar{y}}_r)^2\)</span> = estimated variance of the <strong>residuals</strong></p>
<ul>
<li><p>Dfference between estimated PSU totals, <span class="math inline">\(\hat{t}_i\)</span>, and predicted total based on the ratio estimator, <span class="math inline">\(M_i\hat{\bar{y}}_r\)</span></p></li>
<li><p>No “model” involved, but a residual nonetheless</p></li>
</ul></li>
</ul>


</section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>PUBHBIO 7225</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>